### PR TITLE
rewrite of the display module

### LINKED ISSUE #365: Rewrite display module
[EDIT: generalizing this from a previous idea]

The display module currently plots features/spectrograms in frame or bin units, rather than time or frequency.  This makes it difficult to interact with other data that exist in natural coordinates, or compare results after beat-synchronization, etc, especially when scale changes are non-uniform.

specshow
-------------
[pcolormesh](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.pcolormesh) appears to be a much saner way than `imshow` to handle spectrogram-type inputs.

Switching over would allow the following:

- Much simpler log-scaling using matplotlib primitives
- Native coordinates for nonlinear axes (eg log and beat-synchronous)
- Breaks API
- Remove the `time_ticks` function, and much of the custom axis logic

Relevant to #329 #364 #331 

waveplot
------------
This will be comparatively simpler; we simply need to re-index the frame coordinates in time rather than sample indices.

ticker formatters
---------------------
We can replace most of the various `*_axis` options with a `FuncFormatter` ticker object that applies the appropriate unit transformations.

### PR DESCRIPTION
**Pull request by bmcfee**
Resolves #365 #329 #364 #331 

This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/368)

### CODE REVIEW

**Comment by bmcfee** [comment]
Functionality here is now in place.  All display modes plot in natural coordinates, and ticker functions have been rewritten as `matplotlib.ticker.Formatter` classes.

The tempogram display has been totally redone so that BPM now scales logarithmically upwards, rather than linearly downwards.

This rewrite also fixed a few minor alignment errors, where image pixels at the borders were cropped by 1/2.

A few caveats:

- Log-spaced tickers behave quite differently.  Right now, log-frequency ticks are placed approximately at each C, and do not change gracefully as you change display limits.  This is because the LogLocator behaves substantially differently from AutoLocator/MaxNLocator.  It might be possible to adapt MaxNLocator to work in logarithmic coordinates, but it would be non-trivial.

- Time and Lag tickers now use matplotlib's MaxNLocator rather than a linear locator.  This sometimes breaks down at the edge ticks (ie, last tick may not be displayed), but behaves nicely with limit changes.


TODO:

- Update tests
- Update all plotting-based examples

**Comment by dpwe** [comment]
Reviewed 28 of 30 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[librosa/display.py, line 58 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcIqMq0LERO6blN7PF:-KJcIqMrvGAH-2oMtv5A:-1397775768) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L58)):*
> ```Python
>             # Do we need to tweak vmin/vmax here?
>             sign = '-'
>         else:
> ```

I'm unaware of this convention, and it seems a bit weird.  We want to have negative times available for cross-correlation, but we don't have a way to indicate that, so we wrap around half way by convention?  I'm OK with that.

---

*[librosa/display.py, line 62 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcJD1LoZekjvbxrIJY:-KJcJD1LoZekjvbxrIJZ:135673610) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L62)):*
> ```Python
>             sign = ''
> 
>         if vmax - vmin > 3.6e3:
> ```

.. because 3600.0 would be so weird?

---

*[librosa/display.py, line 74 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcJP7VLUn7VW73IGBO:-KJcJP7Xkj77Qnm-VC5m:89066738) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L74)):*
> ```Python
>             s = '{:g}ms'.format(1e3 * value)
> 
>         return '{:s}{:s}'.format(sign, s)
> ```

Shouldn't the range comparisons be on max(abs(vmax), abs(vmin))?  If my range is 3600 to 3601, we may still want it in minutes:seconds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/368)*

**Comment by bmcfee** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[librosa/display.py, line 58 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcIqMq0LERO6blN7PF:-KJcXzq2yUdZcHeQSbTO:-1218479517) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L58)):*
<details><summary><i>Previously, dpwe (Dan Ellis) wrote…</i></summary>
> I'm unaware of this convention, and it seems a bit weird.  We want to have negative times available for cross-correlation, but we don't have a way to indicate that, so we wrap around half way by convention?  I'm OK with that.
</details>
This "convention" comes from the SMGA-style structure features (segment.lag_to_recurrence / recurrence_to_lag).

---

*[librosa/display.py, line 62 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcJD1LoZekjvbxrIJY:-KJcY9dy1pURMbRrVRN7:620331601) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L62)):*
<details><summary><i>Previously, dpwe (Dan Ellis) wrote…</i></summary>
> .. because 3600.0 would be so weird?
</details>
That's a holdover from when there was also a Frequency ticker scaler, where it was more convenient to express the ranges in scientific notation.  Seemed logical at the time to keep the same style in time_format.

---

*[librosa/display.py, line 74 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcJP7VLUn7VW73IGBO:-KJcYOrqM1nEVXoYwG_a:-1239740642) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L74)):*
<details><summary><i>Previously, dpwe (Dan Ellis) wrote…</i></summary>
> Shouldn't the range comparisons be on max(abs(vmax), abs(vmin))?  If my range is 3600 to 3601, we may still want it in minutes:seconds
</details>
But if your range is 3600 to 3600.5, minutes:seconds is pretty useless except at the extremes of the view interval.  I suppose this could be a user-controllable option, but it would be awkward to express through the specshow api.  (Maybe we don't, and if you want that behavior, it's on you to set up the ticker accordingly.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/368)*

**Comment by bmcfee** [comment]
Most recent changes are docstring updates and expanded tests; I think this is ready to go if the nits are sufficiently picked.

**Comment by bmcfee** [comment]
Review status: 19 of 34 files reviewed at latest revision, 3 unresolved discussions.

---

*[librosa/display.py, line 62 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcJD1LoZekjvbxrIJY:-KJpNKd2nPJQfeTLEdNO:-1554599363) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L62)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> That's a holdover from when there was also a Frequency ticker scaler, where it was more convenient to express the ranges in scientific notation.  Seemed logical at the time to keep the same style in time_format.
</details>
Switched over to use human-readable copmarisons.

Also, dropped the ms formatting after showing it to a few non-audio folks and getting quizzical stares.  s<->mm:ss<->hh:mm:ss seems intuitive enough for almost all applications we care about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/368)*

**Comment by bmcfee** [comment]
@dpwe when you get a minute, could you check over my CR responses?  I think we're done here, but not in any need to rush it.

**Comment by dpwe** [comment]
Reviewed 1 of 3 files at r4, 3 of 15 files at r5.
Review status: 22 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/display.py, line 74 \[r3\]](https://reviewable.io:443/reviews/librosa/librosa/368#-KJcJP7VLUn7VW73IGBO:-KJsN6v2Nj1QWSQhBFPC:-487029754) ([raw file](https://github.com/librosa/librosa/blob/07ac30427ec895ad44b5bc4cc2a7acd2db8b3950/librosa/display.py#L74)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> But if your range is 3600 to 3600.5, minutes:seconds is pretty useless except at the extremes of the view interval.  I suppose this could be a user-controllable option, but it would be awkward to express through the specshow api.  (Maybe we don't, and if you want that behavior, it's on you to set up the ticker accordingly.)
</details>
I don't think switching from "9:20 - 10:40" to "590.00 - 610.00" as you zoom in is a great solution, but I also don't think reaching "10:00 - 10:00" as you zoom in further is great either, as you point out.  I feel we're not really serious about trying to handle ranges that are far offset from zero?  I think what you have is a sensible compromise, one step better than just looking at vmax.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/368)*

**Comment by dpwe** [comment]
I tried to respond in reviewable.  All looks good to me.

  DAn.

**Comment by bmcfee** [comment]
Reviewed 18 of 30 files at r2, 1 of 3 files at r4, 15 of 15 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/368)*

**Pull request merged**
