### PR TITLE
Syntax highlighting

### PR DESCRIPTION
**Pull request by DavidRomanovizc**
#### Any other comments?
Now in all commands and codes examples have syntax highlighting. It is more beautiful than without highlighting

### CODE REVIEW

**Comment by bmcfee** [comment]
I think this is incorrect - almost all of the code blocks are shell script, not python.  Using ` ```python ` will result in incorrect syntax highlighting.

**Comment by DavidRomanovizc** [comment]
> I think this is incorrect - almost all of the code blocks are shell script, not python. Using `` ```python `` will result in incorrect syntax highlighting.

I know, but if we use `sh` or `bash`,  shell scripts will not be highlighted

**Comment by bmcfee** [comment]
Ok, then I think we should leave it as is.

**Review by cr2007 — COMMENTED** [review]
Not all commands are necessarily Python commands though

Ones like `apt-get install ffmpeg` are done in Shell/Bash

```shell
apt-get install ffmpeg
```

**Pull request closed without merging**
