### PR TITLE
[CR] centered frequency bins in specshow

### PR DESCRIPTION
**Pull request by bmcfee**
#### Reference Issue

#586

#### What does this implement/fix? Explain your changes.

This PR modifies the mesh coordinates in `display.specshow` so that CQT bins are centered at their filter frequencies, rather than edge-aligned.

This PR does not (yet) fix the other issue described in #586, where the tick locations are not centered on the bins.  I made an initial attempt at this, but it didn't quite work due to some quirks in how MPL's loglocator class works.  We might have to implement a custom tick locator class for this.

#### Any other comments?

I also fixed FFT display so that it properly returns `n+1` coordinates like all the other modes.  FFT coords are treated a bit differently though, since it doesn't quite make sense to center the DC component (`f=0`), so FFT bins remain left-aligned.  Anyone @stefan-balke @dpwe have ideas for how to handle this case?

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/597)

### CODE REVIEW

**Comment by bmcfee** [comment]
Thinking a bit more about this: do we want to set an explicit policy for how bin locations in specshow should be expected to work?  As mentioned above, the positioning for FFT and CQT are currently pretty different: FFT bins are positioned between `f[i]` and `f[i+1]`, where `f[i]` is the `i`th FFT frequency.  Alternatively, CQT bins are now positioned such that the (vertical) center of bin `i` lies at `c[i]` (the `i`th CQT basis frequency).

Overall, bin-centering makes more sense to me, since it behaves better with overlaid plots in natural coordinate space.  However, applying bin-centering to FFT would require either the vertical axis to go negative (so that the DC bin is centered at 0) or to truncate the DC bin to half-height.  I'm okay with the latter, as long as it's done consistently at the top-end for the nyquist bin.  Of course, having a couple of half-height bins also seems strange, but maybe it's worth it, and people won't notice anyway.

In general, the other axis scalings (tempo, chroma, mel) all seem to call for centered bins, since they're either on a log axis, or the responses of filters with a particular center frequency.

**Comment by dpwe** [comment]
More to the point, drawing the d.c. bin as covering 0 to f_s / n_fft is
just wrong; it covers -f_s/(2n_fft) to +f_s/(2n_fft).

Matlab does indeed use a freq axis that goes negative.

Extending beyond 0..f_s/2 is consistent with having n_fft/2 + 1 bins.

But I'm ok with half-height bins instead.

  DAn.

**Comment by bmcfee** [comment]
Note: the current failures on python 3.4 + numba are due to numba backdating numpy to 1.10 in the 3.4 packages.

**Comment by bmcfee** [comment]
CQT and FFT coordinates are done and lgtm.

To fix: Mel and Tempo coordinates.

**Comment by bmcfee** [comment]
Mel is done now, but tempo is a little strange.

The tempo frequency logic goes like:

```python
t[0] = inf
t[1] = 60 * sr / (hop_length)
t[2] = 60 * sr / (2 * hop_length)
t[k] = 60 * sr / (k * hop_length)
```
In log space (log axis scaling), we get:
```python
log(t[k]) = log(60 * sr / hop_length) - log(k)
```

**Comment by bmcfee** [comment]
Reviewed 1 of 6 files at r1, 4 of 5 files at r2, 18 of 19 files at r4.
Review status: 23 of 24 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/597)*

**Comment by bmcfee** [comment]
I think this one's good to go. The tempo scaler gets a bit weird at the high end since it needs to interpolate between [inf, t_max], but it otherwise seems to properly center the bins.

As mentioned above, the test failure is just a numba distribution issue, and irrelevant to this PR.  Unless there are objections ( @stefan-balke ? ) I'll merge this one tomorrow.

**Comment by bmcfee** [comment]
Stefan's out on vacation; anyone else care to CR this?

**Comment by bmcfee** [comment]
Reviewed 1 of 19 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/597)*

**Pull request merged**
