### PR TITLE
Salience

### PR DESCRIPTION
**Pull request by rabitt**
In progress. Implements #297 

---

This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/427)

### CODE REVIEW

**Comment by rabitt** [comment]
@bmcfee before I write the tests, is this generally what you had in mind?

**Comment by bmcfee** [comment]
@rabitt yeah, more or less.  Thanks for doing this!

I have a couple of thoughts about the api, before you start on tests:

- I wouldn't tie into HPSS here.  Since HPSS is just pre-processing in this application, it could just as easily be called by the user before `salience`.  This would simplify the API.
- Why support complex spectra, if phase information is always discarded?
- Would it be useful to think about generalizing beyond weighted summation?  If so, you might want to check out [`nn_filter`](https://github.com/librosa/librosa/blob/master/librosa/decompose.py#L378), which supports weighted summation as well as generic aggregators (mean, median, max, etc).

In terms of implementation, a few general comments:

- [this line](https://github.com/librosa/librosa/pull/427/files#diff-25de824aab720f5de88a5f1182d98ce6R518) could be implemented more efficiently with numpy masked arrays
- [this line](https://github.com/librosa/librosa/pull/427/files#diff-25de824aab720f5de88a5f1182d98ce6R523) could be implemented more efficiently via `np.average(..., weights=weights)`
- I don't understand the `argrelmax` usage here: comments?

**Comment by rabitt** [comment]
> I wouldn't tie into HPSS here. Since HPSS is just pre-processing in this application, it could just as easily be called by the user before salience. This would simplify the API.

👍 

> Why support complex spectra, if phase information is always discarded?

True. Was copy pasta from another librosa time freq function.

> Would it be useful to think about generalizing beyond weighted summation? If so, you might want to check out nn_filter, which supports weighted summation as well as generic aggregators (mean, median, max, etc).

I don't see why not. Will generalize!

> [this line](https://github.com/librosa/librosa/pull/427/files#diff-25de824aab720f5de88a5f1182d98ce6R518) could be implemented more efficiently with numpy masked arrays

Haven't used maked arrays before but took a quick look at the documentation.  Are you thinking something like this?
```python
import numpy.ma

if peak_filter:
    peak_mask = np.ones(S_harm.shape)
    peak_mask[:, S_peaks[0], S_peaks[1]] = 0
else:
    peak_mask = np.zeros(S_harm.shape)

S_mask = ma.masked_array(S_harm, mask=peak_mask)

S_sal = (S_mask.T * weights).T.sum(axis=0)
```

> [this line](https://github.com/librosa/librosa/pull/427/files#diff-25de824aab720f5de88a5f1182d98ce6R523) could be implemented more efficiently via np.average(..., weights=weights)

👍 

> I don't understand the argrelmax usage here: comments?

This is the optional "peak filtering" stage. Essentially, the anything that is not a peak in frequency in the original input representation is zeroed out and not included in the final salience computation. If you try out `salience(..., peak_filter=True)` vs `salience(..., peak_filter=False)` you'll see that just doing a harmonic sum makes the final representation very noisy.

**Comment by rabitt** [comment]
@bmcfee any idea why the tests are failing? Does `core.harmonic` need to be added to some init file?

**Comment by bmcfee** [comment]
From [the log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/171651962/log.txt):

```
======================================================================
ERROR: test_core.test_salience
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/env/miniconda2.7/envs/test-environment/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/librosa/librosa/tests/test_core.py", line 288, in test_salience
    S_sal = librosa.core.salience(S, freqs, harmonics, weights)
  File "/home/travis/build/librosa/librosa/librosa/core/spectrum.py", line 522, in salience
    S_mask = np.sma.masked_array(S_harm, mask=peak_mask)
AttributeError: 'module' object has no attribute 'sma'
```

**Comment by rabitt** [comment]
Ahh sorry @bmcfee I sent that before the round of testing you're referencing finished. From the [log before](https://travis-ci.org/librosa/librosa/jobs/171537892#L685-L699):

```bash
======================================================================
ERROR: test_cache.test_cache_enabled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/env/miniconda2.7/envs/test-environment/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/librosa/librosa/tests/test_cache.py", line 61, in test_cache_enabled
    import librosa.cache
  File "/home/travis/build/librosa/librosa/librosa/__init__.py", line 15, in <module>
    from . import core
  File "/home/travis/build/librosa/librosa/librosa/core/__init__.py", line 95, in <module>
    from .spectrum import *  # pylint: disable=wildcard-import
  File "/home/travis/build/librosa/librosa/librosa/core/spectrum.py", line 12, in <module>
    from . import harmonic
ImportError: cannot import name harmonic
```

I'm importing `harmonic` the same way as `time_frequency` and I looked through the inits and don't see an obvious reason why `harmonic` is failing to import but `time_frequency` is fine.

**Comment by bmcfee** [comment]
That's odd.  FWIW, I think this function makes more sense living inside the harmonic submodule anyway.  Maybe migrating there would resolve this?

**Comment by rabitt** [comment]
@bmcfee trying to debug this, but I'm seeing an [empty log](https://travis-ci.org/librosa/librosa/jobs/172416393)? Is this just me?

**Comment by bmcfee** [comment]
Doesn't look empty to me: [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/172416393/log.txt)

**Comment by rabitt** [comment]
@bmcfee This is good to go

**Comment by bmcfee** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[librosa/core/harmonic.py, line 72 at r1](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyNW_faVsxlp1q8TLc:-KWyNW_faVsxlp1q8TLd:b9ps2h1) ([raw file](https://github.com/librosa/librosa/blob/a32425810552f765592c227cfefdd5273238a115/librosa/core/harmonic.py#L72)):*
> ```Python
>     (1025, 646)
> 
>     >>> plt.figure()
> ```

I think you need to put an `import matplotlib.pyplot as plt` in here for the docs to properly generate images from examples here.

---

*[librosa/core/harmonic.py, line 79 at r1](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyNyh8mfxQf7USoKts:-KWyNyh9X55mQgnUMxPZ:b-igxatz) ([raw file](https://github.com/librosa/librosa/blob/a32425810552f765592c227cfefdd5273238a115/librosa/core/harmonic.py#L79)):*
> ```Python
> 
>     """
>     if aggregate is None or aggregate == np.average:
> ```

should be `is np.average` not `==`

---

*[librosa/core/harmonic.py, line 84 at r1](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyNekLsCjOlMNlg3Z1:-KWyNekLsCjOlMNlg3Z2:b1mpbuu) ([raw file](https://github.com/librosa/librosa/blob/a32425810552f765592c227cfefdd5273238a115/librosa/core/harmonic.py#L84)):*
> ```Python
>     weights = np.array(weights, dtype=float)
> 
>     S_harm = harmonics(S, freqs, harmonic_vals, kind='quadratic')
> ```

Can you make `kind` a pass-through keyword argument instead of hard-coding it?  Also the default value should match `harmonics` for consistency.

---

*[librosa/core/harmonic.py, line 98 at r1](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyO3o2mKTH5lZRSfA7:-KWyO3o2mKTH5lZRSfA8:b-tekm07) ([raw file](https://github.com/librosa/librosa/blob/a32425810552f765592c227cfefdd5273238a115/librosa/core/harmonic.py#L98)):*
> ```Python
>         S_sal = aggregate(S_mask, axis=0, weights=weights)
>     else:
>         S_sal = aggregate(S_mask, axis=0)
> ```

If `aggregate` is not `np.average`, `weights` is not used.  Does it make sense to keep `weights` as a required argument?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by bmcfee** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[librosa/core/harmonic.py, line 84 at r1](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyNekLsCjOlMNlg3Z1:-KWySzWHN7yK1dv4VfyM:b-2y7rsl) ([raw file](https://github.com/librosa/librosa/blob/a32425810552f765592c227cfefdd5273238a115/librosa/core/harmonic.py#L84)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Can you make `kind` a pass-through keyword argument instead of hard-coding it?  Also the default value should match `harmonics` for consistency.
</details>
... can you also make the variable name match? :grin: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[librosa/core/harmonic.py, line 21 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiLdg4GGHro4Pqbii:-KWyiLdg4GGHro4Pqbij:b-t5pjeq) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L21)):*
> ```Python
>     S : np.ndarray [shape=(d, n)]
>         input time frequency magnitude representation (stft, ifgram, etc).
>         Must be real-valued.
> ```

Should it be non-negative as well?

---

*[librosa/core/harmonic.py, line 25 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiQpqkQ92x3QZ4LVR:-KWyiQpqkQ92x3QZ4LVS:b-6wtckz) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L25)):*
> ```Python
>     freqs : np.ndarray, shape=(X.shape[axis])
>         The frequency values corresponding to X's elements along the
>         chosen axis.
> ```

There is no provision here for the user to select an axis.

---

*[librosa/core/harmonic.py, line 30 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiddFQAJEGtNWQ0ED:-KWyiddFQAJEGtNWQ0EE:b-sorq15) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L30)):*
> ```Python
>         Harmonics to include in salience computation.  The first harmonic (1)
>         corresponds to `S` itself. Values less than one (e.g., 1/2) correspond
>         to sub-harmonics.
> ```

can this be renamed to match the corresponding parameter in `harmonics`?

---

*[librosa/core/harmonic.py, line 34 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiiRf4H7hRMrlPK9r:-KWyiiRf4H7hRMrlPK9s:by2v10o) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L34)):*
> ```Python
>     weights : list-like
>         The weight to apply to each harmonic in the summation.
>         Must be the same length as `harmonics`.
> ```

Specify default behavior if not provided

---

*[librosa/core/harmonic.py, line 39 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyimzxixk8Ts_cC-1r:-KWyimzxixk8Ts_cC-1s:bgs13sv) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L39)):*
> ```Python
>         aggregation function (default: `np.mean`)
>         If `aggregate=np.average`, then a weighted average is
>         computed according to the (per-row) weights in `rec`.
> ```

Is it per-row or per-harmonic?

---

*[librosa/core/harmonic.py, line 44 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyirDyDedYOf2gHpDj:-KWyirDyDedYOf2gHpDk:b-g1u80j) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L44)):*
> ```Python
> 
>     filter_peaks : bool
>         If true, computes harmonic summation only on peaks in frequency.
> ```

frequencies of peak magnitude

---

*[librosa/core/harmonic.py, line 49 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiwYq_d0IAFKpahQ0:-KWyiwYq_d0IAFKpahQ1:bxofxlt) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L49)):*
> ```Python
> 
>     kind : str
>         Interpolation type. See `scipy.interpolate.interp1d`.
> ```

Interpolation type +for harmonic estimation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by rabitt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[librosa/core/harmonic.py, line 21 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiLdg4GGHro4Pqbii:-KWyk1Uw6FpdV_T3H9CT:b-h3vzra) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L21)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Should it be non-negative as well?
</details>
It could be negative in theory (nothing will break)

---

*[librosa/core/harmonic.py, line 44 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyirDyDedYOf2gHpDj:-KWyl-kJ7iTbbVu5uAy1:b-k8oa47) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L44)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> frequencies of peak magnitude
</details>
I'm not sure what you're asking for here. "If true, computes harmonic summation only on peaks in frequency." --> "If true, computes harmonic summation only on frequencies of peak magnitude." ? If so I thinks clearer the way it is now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by rabitt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[librosa/core/harmonic.py, line 30 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiddFQAJEGtNWQ0ED:-KWymKHqSQLdAD0BqHCu:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L30)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> can this be renamed to match the corresponding parameter in `harmonics`?
</details>
Done.

---

*[librosa/core/harmonic.py, line 34 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiiRf4H7hRMrlPK9r:-KWymItjzlDEQ1n1Uvej:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L34)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Specify default behavior if not provided
</details>
Done.

---

*[librosa/core/harmonic.py, line 39 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyimzxixk8Ts_cC-1r:-KWymI1Vb7jO6-T3bxZx:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L39)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Is it per-row or per-harmonic?
</details>
Done.

---

*[librosa/core/harmonic.py, line 49 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiwYq_d0IAFKpahQ0:-KWymGI0GAdoAR2D1v-0:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L49)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Interpolation type +for harmonic estimation
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by bmcfee** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[librosa/core/harmonic.py, line 21 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiLdg4GGHro4Pqbii:-KX12EGj6QgqAaL1sFUf:b-k8sx5t) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L21)):*
<details><summary><i>Previously, rabitt (Rachel Bittner) wrote…</i></summary>
> It could be negative in theory (nothing will break)
</details>
But it says "magnitude" which implies non-negative.  Just looking for consistency in the docs.

---

*[librosa/core/harmonic.py, line 44 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyirDyDedYOf2gHpDj:-KX12Whl7YPatrjdQaGX:b-wcx1qg) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L44)):*
<details><summary><i>Previously, rabitt (Rachel Bittner) wrote…</i></summary>
> I'm not sure what you're asking for here. "If true, computes harmonic summation only on peaks in frequency." --> "If true, computes harmonic summation only on frequencies of peak magnitude." ? If so I thinks clearer the way it is now.
</details>
"peaks in frequency" to me reads as "highest frequency" because there's no mention of magnitude.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by bmcfee** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/core/harmonic.py, line 21 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiLdg4GGHro4Pqbii:-KX6e8obxJ913b4MBuD6:b-tcnznl) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L21)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> But it says "magnitude" which implies non-negative.  Just looking for consistency in the docs.
</details>
*positive->non-negative :grin: (zeros are allowed, right?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by rabitt** [comment]
*[librosa/core/harmonic.py, line 21 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiLdg4GGHro4Pqbii:-KX3YEYEFWwtB9kQiZuz:b6vis3u) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L21)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> *positive->non-negative :grin: (zeros are allowed, right?)
</details>
Ya killin me smalls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by bmcfee** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/core/harmonic.py, line 21 at r2](https://reviewable.io:443/reviews/librosa/librosa/427#-KWyiLdg4GGHro4Pqbii:-KX6kFSMv-ECCFkD3zgO:b9u8pxo) ([raw file](https://github.com/librosa/librosa/blob/7dcb73bb64507f3d1f979feeb44363dab6f5ced2/librosa/core/harmonic.py#L21)):*
<details><summary><i>Previously, rabitt (Rachel Bittner) wrote…</i></summary>
> Ya killin me smalls
</details>


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/427)*

**Pull request merged**
