### PR TITLE
adding axes kwarg

### PR DESCRIPTION
**Pull request by choldgraf**
This is a first-pass at adding the ability to pre-specify a matplotlib axis object when doing plotting. This way you can do

```
fig, ax = plt.subplots()
lr.myplotfunction(..., axes=ax)
```

LMK how this looks (or if I'm missing any functions this could be added to)

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/689)

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks @choldgraf !  You perhaps missed that there's already a PR for this open? #687 

Maybe you two can team up?

**Comment by choldgraf** [comment]
Whoops! No I did not see that haha. Don't think I can push to their pr, but
happy to do so if I can be of help there.

**Comment by choldgraf** [comment]
Actually that pr looks pretty much ready to go. I'm not sure how I could give input in a way that wouldn't add unnecessary complexity to the pr (it seems like a good enough solution)... I think I'll just close this one but please do ping me if there's something specific I can do there

**Comment by friesch** [comment]
@choldgraf I added your example to the PR. Anything else you want me to add?

**Pull request closed without merging**
