### PR TITLE
070 cleanups

### LINKED ISSUE #804: Extend MFCC docs
The question of non-default hop sizes etc. for MFCC extraction comes up frequently.

Maybe we should add an example to the MFCC docs where we vary the `melspectrogram` parameters.

### PR DESCRIPTION
**Pull request by bmcfee**
#### Reference Issue
Fixes #804 #874 #875 #896 

#### What does this implement/fix? Explain your changes.

Mostly expanding documentation, and one change to the requirements list.  No functional changes.

### CODE REVIEW

**Comment by lostanlen** [comment]
should we start warning Python 2.7 users that librosa 1.0 will only support Python 3?

**Comment by bmcfee** [comment]
> should we start warning Python 2.7 users that librosa 1.0 will only support Python 3?

I'd rather warn that 0.7 is the last release supporting legacy python, but sure.  (Still TBD when 1.0 will come out, if ever :))

**Comment by bmcfee** [comment]
I think this is good to go.  @lostanlen ?

**Comment by lostanlen** [comment]
yeah! :shipit:  :shipit:  :shipit:

**Pull request merged**
