### PR TITLE
Allow precomputing distance matrix in librosa.core.dtw

### PR DESCRIPTION
**Pull request by cghawthorne**
Modifies librosa.core.dtw to allow passing in a precomputed distance matrix. 

Useful if you want to calculate the penalty based on the distance matrix, similar to https://github.com/craffel/pretty-midi/blob/master/examples/align_midi.py

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/574)

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for this!  It generally looks good to me, with one minor formatting issue.

Tagging @stefan-balke for an extra set of eyeballs.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/core/dtw.py, line 175 at r1](https://reviewable.io:443/reviews/librosa/librosa/574#-KkCZFW6-Lqxr_yTVgjH:-KkCZFW70r12ITnaYzTC:b-8ny3id) ([raw file](https://github.com/librosa/librosa/blob/5f807d0cd8d532ca32b702b8b483ebf262468c5b/librosa/core/dtw.py#L175)):*
> ```Python
>     if weights_mul is None:
>         weights_mul = np.array([1, 1, 1])
> ```

Please adjust your indents to 4 spaces to match the rest of the package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/574#-:-KkCZJv8cthoYKeR7F3q:b-cnq5uv)*

**Comment by stefan-balke** [comment]
Yes, LGTM!

**Comment by cghawthorne** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/core/dtw.py, line 175 at r1](https://reviewable.io:443/reviews/librosa/librosa/574#-KkCZFW6-Lqxr_yTVgjH:-KkJ16XFA1hdNSFwf_IS:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/5f807d0cd8d532ca32b702b8b483ebf262468c5b/librosa/core/dtw.py#L175)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Please adjust your indents to 4 spaces to match the rest of the package.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/574)*

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/574)*

**Comment by bmcfee** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/574#-:-KkM4g95490ghAktAfe8:bnfp4nl)*

**Comment by bmcfee** [comment]
Thanks for this!

**Pull request merged**
