### PR TITLE
updates C2 =~ 32.7Hz typo in chroma cqt and chroma cens functions

### LINKED ISSUE #466: C2 is not 32.7 Hz?
Sorry if this is nitpicky but appears that the docs for [chroma cqt](http://librosa.github.io/librosa/generated/librosa.feature.chroma_cqt.html) and [chroma cens](http://librosa.github.io/librosa/generated/librosa.feature.chroma_cens.html) both list C2 as 32.7 Hz. Could lead to people making a mistake when it is actually 65.41 Hz.

I'm not sure which of the two is the actual value otherwise I'd submit a PR!

### PR DESCRIPTION
**Pull request by polyrhythmatic**
Fixes #466

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/467)

### CODE REVIEW

**Comment by bmcfee** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/feature/spectral.py, line 879 at r1](https://reviewable.io:443/reviews/librosa/librosa/467#-KYPcl5u6LD6oGas70oh:-KYPcl5u8weZMFK3FuNe:b-bqfj4w) ([raw file](https://github.com/librosa/librosa/blob/f83edd7f94dff3b01e783fd3e830d89f6fb9d611/librosa/feature/spectral.py#L879)):*
> ```Python
>         minimum frequency to analyze in the CQT.
>         Default: C1' ~= 32.7 Hz
> ```

Looks like a missing quote mark here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/467)*

**Comment by polyrhythmatic** [comment]
well... that was pretty silly. Should be updated now

**Comment by bmcfee** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/467#-:-KYPvDwN6bZ7R29G6jCu:bnfp4nl)*

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/467)*

**Comment by bmcfee** [comment]
Merged.  Thanks!

**Pull request merged**
