### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by raccoonML**
#### What does this implement/fix? Explain your changes.
Happy new year! Time to update the copyright in the license.

#### Any other comments?
Related: #1531

### CODE REVIEW

**Review by lostanlen — APPROVED** [review]
nice ... :)

**Review by bmcfee — CHANGES_REQUESTED** [review]
Thanks for this - can you also update the notice in the documentation config? https://github.com/librosa/librosa/blob/71bb1942093805a429aa68bec5b30912b82082a4/docs/conf.py#L200

**Comment by raccoonML** [comment]
Done. It looks like these are the only two instances of a hardcoded copyright date in the repo.

**Review by bmcfee — APPROVED** [review]

**Comment by bmcfee** [comment]
Thanks for the updates!

**Comment by lostanlen** [comment]
Thank you for this @raccoonML 
Happy 2023 everyone!

**Pull request merged**
