### PR TITLE
Use generator expression instead of making a list

### PR DESCRIPTION
**Pull request by carlthome**
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/544)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/544)*

**Comment by bmcfee** [comment]
LGTM.  Confirmed that the build fails are due to #539 and this change does not affect tests otherwise.

Is there anything else to include for this one?

**Comment by carlthome** [comment]
Nope, just a minor syntax fix to avoid creating a list. Should be safe for merge.

**Comment by bmcfee** [comment]
Thanks!

**Pull request merged**
