### PR TITLE
fix: dtw(C=C,subseq=True) doesn't work

### PR DESCRIPTION
**Pull request by viktorAndreevichMorozov**
#### Reference Issue
Fixes https://github.com/librosa/librosa/issues/869

#### What does this implement/fix? Explain your changes.

Just get dimensions from C ndarray (which is always computed anyway), not from X and Y (thous are optional).

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for noting this and making the PR.  Please add a bit more description of what the problem was though, since this did not have an existing reference issue.

Also it appears that the proposed change is breaking tests, so please look into that before we do a proper code review.

**Comment by viktorAndreevichMorozov** [comment]
Hello. It is the fix for issue https://github.com/librosa/librosa/issues/869 . With the last commit it passes all tests.

**Comment by bmcfee** [comment]
Thanks!  This looks fine to me, but it would be great if you could add a test case to cover the previously unchecked behavior.  @stefan-balke care to chime in on this?

**Comment by stefan-balke** [comment]
Good catch. But a test would be nice. Provide a ground-truth `C` and let it run. Should give the same result as with providing `X` and `Y`.

**Comment by viktorAndreevichMorozov** [comment]
I wrote the test.

**Comment by bmcfee** [comment]
Perfect, this looks good to me.  Thanks again @viktorAndreevichMorozov !

**Pull request merged**
