### PR TITLE
Fix db_to_amplitude docs

### PR DESCRIPTION
**Pull request by i-aki-y**
#### What does this implement/fix? Explain your changes.

I modified two docs about `db_to_amplitude` and `amplitude_to_db`.

1. Fix an equation explaining the behavior of `db_to_amplitude`.
2. Improve the explanation of `amplitude_to_db` to make it more informative.

I appreciate it if you review this.

(1) The equation about  `db_to_amplitude` looks wrong. That should be fixed in the following way:

```
   db_to_amplitude(S_db) ~= 10.0**(0.5 * (S_db + log10(ref)/10))
-> db_to_amplitude(S_db) ~= 10.0**(0.5 * S_db/10 + log10(ref))

```

This is a piece of evidence:

```python
from numpy import log10
S_db = 10
ref = 5
print("Actual :", librosa.db_to_amplitude(S_db, ref=ref))
print("Current:", 10.0**(0.5 * (S_db + log10(ref)/10)))
print("Fixed  :", 10.0**(0.5 * S_db/10 + log10(ref)))

# Actual : 15.811388300841896
# Current: 108379.8386734369
# Fixed  : 15.811388300841895
```

(2) Adding information about `ref` and `amin` is helpful.  Because I think there are some possibilities, like `power_to_db(S**2, ref**2, amin**2)` or `power_to_db(S**2, ref, amin)`, but it is difficult to say which is employed without seeing source code.

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for this!  Do you think there is anything we should change regarding `power_to_db`'s documentation for the sake of consistency?

**Comment by i-aki-y** [comment]
@bmcfee I looked into the descriptions of `power_to_db` and `db_to_power`, and I think explanations are consistent and make sense to me.

**Comment by bmcfee** [comment]
Great, thanks!  This LGTM, is there anything else to add here, or should we merge?

**Comment by i-aki-y** [comment]
@bmcfee Thank you for your review.

I added minor fixes to reduce ambiguity. 
```diff
# in doc for top_db parameter
- max(10 * log10(S)) - top_db 
+ max(10 * log10(S/ref)) - top_db

# in doc for amplitude_to_db
- power_to_db(S**2, ref=ref**2, amin=amin**2)
+ power_to_db(S**2, ref=ref**2, amin=amin**2, top_db)
```
These might be redundant, but I think they do not lose original readability.

I have done what I can do in this PR. If you do not find any issue in my PR, I wish this would be merged.

**Review by lostanlen — APPROVED** [review]

**Comment by i-aki-y** [comment]
@bmcfee Thanks! I fixed it.

**Comment by bmcfee** [comment]
Thanks again @i-aki-y for this!  Everything LGTM so I'm happy to merge.

**Pull request merged**
