### PR TITLE
removed features slated for removal in 0.6.0

### PR DESCRIPTION
**Pull request by bmcfee**
#### Reference Issue
Fixes: #626 

#### What does this implement/fix? Explain your changes.

This PR removes deprecated functions slated for removal in 0.6.0.  It introduces breaking changes.

#### Any other comments?

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/627)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/627)*

**Comment by bmcfee** [comment]
TODO: audit docs / examples for references to deprecated functions/parameters:

- [ ] `cqt(real=)`
- [ ] `logamplitude`
- [ ] `estimate_tempo`
- [ ] `rmse(n_fft=)`

**Comment by stefan-balke** [comment]
Planning to have a release in time for ISMIR?

**Comment by bmcfee** [comment]
Notn really, but before the end of the year would be nice.

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/627)*

**Comment by bmcfee** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/627)*

**Pull request merged**
