### PR TITLE
Include LICENSE.md in sdists

### PR DESCRIPTION
**Pull request by toddrme2178**
The ISC license requires that the license be included in all copies of the code.  Also include the AUTHORS.md and CONTRIBUTING.md files.

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/777)

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for catching this.  Is there anything else that needs changing here, or is this PR complete?

**Comment by toddrme2178** [comment]
It should be complete.

>

**Comment by bmcfee** [comment]
Merged.  Thanks again!

**Comment by lostanlen** [comment]
Hey @toddrme2178! Thanks again for doing this. Would you mind sharing your full name (first name and last name) so that you're properly credited in the release notes of librosa v0.6.3? That will also allow us to produce a DOI for the Zenodo release. Thank you :)

**Pull request merged**
