### PR TITLE
Minor fix on string 59

### PR DESCRIPTION
**Pull request by kant**
#### Reference Issue

There is no related issue. 

#### What does this implement/fix? Explain your changes.
There is a typo on string 59. Plus a question: on string 94: `Windows: download binaries from the website`(...) the URL is https://gstreamer.freedesktop.org/ ?

#### Any other comments?
There is no break on code, so, no collateral damage at sight.

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks @kant !  LGTM unless there's anything else you wan to add here.

**Comment by bmcfee** [comment]
Sorry I just noticed your question -- yeah, that's correct.  If you want to roll that change in too, that'd be great.

You can also bypass tests here since it's just readme changes, by adding `[ci skip]` to the commit message.

**Comment by kant** [comment]
I'll do a pull request adding  https://gstreamer.freedesktop.org/ ?

**Comment by bmcfee** [comment]
You can just add on to this one, thanks!

**Pull request merged**
