### PR TITLE
Exception error message change, minor PEP8 formatting

### PR DESCRIPTION
**Pull request by jack-alexander-ie**
#### What does this implement/fix? Explain your changes.
I implement a RuntimeError message in audio.py to comply with PEP8's no blank exception rule. I also made some other small PEP8 changes - such as removing excess blank space and adding space between functions.

#### Any other comments?
This is my first commit to the project and I've tried to stick to the rules as best I could. Any advice would be very welcome!

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for doing this -- I'm curious if you intentionally closed this issue out?

A couple of other things:

1. This conflicts with a currently outstanding PR on audio.py #872, which already fixes the bare exception.
2. We don't strictly adhere to PEP8, but take it as advise (in the spirit of the hobgoblins clause).  That said, your changes seem fine and improve readability, so I'm in favor of them.
3. Can you remove those xml files from the PR?

Anyway, thanks again for this!

**Comment by jack-alexander-ie** [comment]
No problem! I'd closed it accidentally following the pull request..apologies.

**Comment by jack-alexander-ie** [comment]
> Thanks for doing this -- I'm curious if you intentionally closed this issue out?
> 
> A couple of other things:
> 
> 1. This conflicts with a currently outstanding PR on audio.py #872, which already fixes the bare exception.
> 2. We don't strictly adhere to PEP8, but take it as advise (in the spirit of the hobgoblins clause).  That said, your changes seem fine and improve readability, so I'm in favor of them.
> 3. Can you remove those xml files from the PR?
> 
> Anyway, thanks again for this!

Thanks for the feedback!

1. My mistake, will look out for this in future.
2. That's great - hopefully I can contribute a little more effectively down the line.
3. They should be remove in this PR

**Comment by bmcfee** [comment]
Thanks @jack-alexander-ie !  This looks good to me -- is there anything else you want to add to this PR before merging?

**Comment by jack-alexander-ie** [comment]
Great! I think that's it for the moment. I'll tinker and see if I can work on some of the 'good for beginners' issues, but will do another PR for them.

**Comment by bmcfee** [comment]
Cool, thanks again!

**Pull request merged**
