### PR TITLE
Documenting advanced io use cases

### PR DESCRIPTION
**Pull request by faroit**
This PR adds additional documentation for advanced use case described in #420 

Mainly this documentation should address that many users have filed issues about i/o problems. 
Specifically:

* Block processing #116
* Output compression #70
* File-like input #140
* PCM subformats #361

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/480)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/ioformats.rst, line 3 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8Vg2_h1nJEfLvmROq:-KZ8Vg2_h1nJEfLvmROr:bq05hya) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L3)):*
> ```reStructuredText
> Advanced I/O Use Cases
> =====================
> ```

Separator is one char short

---

*[docs/ioformats.rst, line 12 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8VpAiSlFW1r689vPW:-KZ8VpAiSlFW1r689vPX:b-dkjz35) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L12)):*
> ```reStructuredText
> *librosa* uses `audioread <https://github.com/sampsyo/audioread>`_ for reading audio. While we chose this library for best flexibility and support of various compressed formats like MP3; some specific formats might not be supported. Especially specific WAV subformats like 24bit PCM or 32bit float might cause problems depending on your installed audioread codecs. *libsndfile* covers a `bunch of these formats <http://www.mega-nerd.com/libsndfile/>`_.
> 
> Reading audio files using pysoundfile is silimar to the method in *librosa*. One important difference is that the read data is of shape ``(nb_samples, nb_channels)`` compared to ``(nb_channels, nb_samples)`` in :func:`<librosa.core.load>`, hence it should be transposed for further processing in *librosa*.
> ```

silimar -> similar

Also, describe `soundfile` as a python wrapper to `libsndfile` and provide a link.

---

*[docs/ioformats.rst, line 25 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WR56WCMQpvOzoqTZ:-KZ8WR56WCMQpvOzoqT_:b3syxsk) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L25)):*
> ```reStructuredText
>     data, samplerate = sf.read(filename)
>     data = data.T
> ```

Note that this is not equivalent to librosa's loader, since it uses the file's native sampling rate.  Maybe give an example including resampling to a target sr as well.

---

*[docs/ioformats.rst, line 31 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8W-t7e12zWPleQaKC:-KZ8W-t7e12zWPleQaKD:b-ygx5m) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L31)):*
> ```reStructuredText
> -----------------
> 
> For large audio signal it could be benficial to not load the whole audio file
> ```

signals

---

*[docs/ioformats.rst, line 46 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8W9gRJ2s4FL8zUkNF:-KZ8W9gRJ2s4FL8zUkNG:bxol1y9) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L46)):*
> ```reStructuredText
>     rate = sf.info('stereo_file.wav').samplerate
> 
>     chromas = [chroma_stft(y=np.mean(bl, axis=1), sr=rate) for bl in block_gen]
> ```

This needs a comment explaining why you're averaging over the block (channels)

---

*[docs/ioformats.rst, line 48 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WEP8dOF9bjTfnQUJ:-KZ8WEP8dOF9bjTfnQUK:b2eig9y) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L48)):*
> ```reStructuredText
>     chromas = [chroma_stft(y=np.mean(bl, axis=1), sr=rate) for bl in block_gen]
> 
> .. note:: See installation instruction for PySoundfile `here <http://pysoundfile.readthedocs.io>`_.
> ```

Move psf install directions up to the top

---

*[docs/ioformats.rst, line 68 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WLD2y3AdiRfladwq:-KZ8WLD2y3AdiRfladwr:btibvkv) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L68)):*
> ```reStructuredText
>     with zf.ZipFile('test.zip') as myzip:
>         with myzip.open('stereo_file.wav') as myfile:
>             tmp = io.BytesIO(myfile.read())
> ```

Does this work in both py2 and py3?  I seem to recall there being some differences with bytesIO

---

*[docs/ioformats.rst, line 80 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8W_n_nLscwEo7JgFb:-KZ8W_naZ83VFyC34YHN:b-rlo7lw) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L80)):*
> ```reStructuredText
>     import io
> 
>     from urllib.request import urlopen
> ```

this will also cause problems in py3

---

*[docs/ioformats.rst, line 84 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WciwcT15ohnCJQ-d:-KZ8WciwcT15ohnCJQ-e:b-zbcf7p) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L84)):*
> ```reStructuredText
>     url = "https://raw.githubusercontent.com/librosa/" +
>       "librosa/master/tests/data/test1_44100.wav"
> ```

+ is unnecessary here if you wrap in parentheses

---

*[docs/ioformats.rst, line 88 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8Whf1BOstQ8Ery_Kc:-KZ8Whf1BOstQ8Ery_Kd:b-2246rf) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L88)):*
> ```reStructuredText
> 
> 
> .. warning:: This is a example does only work in python 3. For python 2 please use ``from urllib2 import urlopen``.
> ```

rewrite it using `six` to handle the version discrepancies

---

*[docs/ioformats.rst, line 91 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WlRG_QtKAFk80P_8:-KZ8WlRG_QtKAFk80P_9:buv24c1) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L91)):*
> ```reStructuredText
> 
> .. note:: See installation instruction for PySoundfile `here <http://pysoundfile.readthedocs.io>`_.
> ```

we don't need the install link everywhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/480)*

**Comment by bmcfee** [comment]
Thanks for doing this!  I added a bunch of minor comments, but it overall looks great.

**Comment by faroit** [comment]
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/ioformats.rst, line 3 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8Vg2_h1nJEfLvmROq:-KZCy_rpFbD_WpD4s39w:bgoc8w) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L3)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Separator is one char short
</blockquote></details>

Done. (markdown guy)

---

*[docs/ioformats.rst, line 12 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8VpAiSlFW1r689vPW:-KZCymlTsC_Ea0C3vrVI:b-836nyq) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L12)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

silimar -> similar

Also, describe `soundfile` as a python wrapper to `libsndfile` and provide a link.
</blockquote></details>

right, I've added an additional description

---

*[docs/ioformats.rst, line 25 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WR56WCMQpvOzoqTZ:-KZCz0SV4GWoM4M5qnXH:b-fhkesz) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L25)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Note that this is not equivalent to librosa's loader, since it uses the file's native sampling rate.  Maybe give an example including resampling to a target sr as well.
</blockquote></details>

but this would include using resampy, because resampling is not supported out of the box in pysoundfile. What do you thin?

---

*[docs/ioformats.rst, line 31 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8W-t7e12zWPleQaKC:-KZCzAUZWi6cCG5JTUv7:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L31)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

signals
</blockquote></details>

Done.

---

*[docs/ioformats.rst, line 46 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8W9gRJ2s4FL8zUkNF:-KZCzBmP2gyanne00eqp:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L46)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

This needs a comment explaining why you're averaging over the block (channels)
</blockquote></details>

Done.

---

*[docs/ioformats.rst, line 48 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WEP8dOF9bjTfnQUJ:-KZCzEPEN14jfGqUrxud:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L48)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Move psf install directions up to the top
</blockquote></details>

Done.

---

*[docs/ioformats.rst, line 68 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WLD2y3AdiRfladwq:-KZCzGQv0cMjghnV872n:b-rcboo7) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L68)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Does this work in both py2 and py3?  I seem to recall there being some differences with bytesIO
</blockquote></details>

bytesIO does work in both version. They differ in String handling

---

*[docs/ioformats.rst, line 80 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8W_n_nLscwEo7JgFb:-KZCzQzv2tLJGS1fItfH:bevtnwe) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L80)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

this will also cause problems in py3
</blockquote></details>

alright, i've used six here

---

*[docs/ioformats.rst, line 84 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WciwcT15ohnCJQ-d:-KZCzX7pL_3RzseeshQg:bv6fnpz) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L84)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

+ is unnecessary here if you wrap in parentheses
</blockquote></details>

I think a long line is okay here

---

*[docs/ioformats.rst, line 88 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8Whf1BOstQ8Ery_Kc:-KZCzZrCIU9Lj-cGG9Tq:b-7rl0jd) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L88)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

rewrite it using `six` to handle the version discrepancies
</blockquote></details>

done.

---

*[docs/ioformats.rst, line 91 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WlRG_QtKAFk80P_8:-KZCzeRxYszVHQ_4-dZk:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L91)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

we don't need the install link everywhere
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/480)*

**Comment by bmcfee** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/ioformats.rst, line 25 at r2](https://reviewable.io:443/reviews/librosa/librosa/480#-KZ8WR56WCMQpvOzoqTZ:-KZEaW5RZgJDrTsEYhNm:b9qgh5r) ([raw file](https://github.com/librosa/librosa/blob/5067d840eb9b26f0843a5605be7829b4c3342b53/docs/ioformats.rst#L25)):*
<details><summary><i>Previously, faroit (Fabian-Robert Stöter) wrote…</i></summary><blockquote>

but this would include using resampy, because resampling is not supported out of the box in pysoundfile. What do you thin?
</blockquote></details>

That's okay. You could also do it via `librosa.resample`. it uses resampy under the hood, but saves the user from needing to know what resampy is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/480)*

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/480)*

**Comment by bmcfee** [comment]
This seems good to me.  @faroit is there anything else you'd like to add, or shall I merge?

**Comment by faroit** [comment]
I've added resampling to the load example and also I forgot that librosa loads as `np.float32` by default, So I've added this as well.

Should be good to merge now 🎄 🎅 🎁

**Comment by bmcfee** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/480#-:-KZweZR3oqrig1A4Re-g:bnfp4nl)*

**Comment by bmcfee** [comment]
Merged.  Thanks @faroit !

**Pull request merged**
