### PR TITLE
made smoothing optional, allowed overriding smoothing window function

### LINKED ISSUE #728: Make smoothing optional in chroma_cens
#### Description
`chroma_cens` applies two post-processing steps to chroma features:

1. non-linear amplitude warping by quantization
2. temporal smoothing

Much of the functionality is hard-coded into the implementation right now, but could be exposed to give the user more flexibility.  Specifically, I'm thinking of allowing the user to bypass the smoothing operation (`win_len_smooth=None`), and/or override the default window function (`hann`) by a user-specified descriptor.  Setting `win_len_smooth=1` doesn't exactly work because it gets expanded by 2 before convolution.

This way, you can easily measure the changes due to quantization and smoothing.

(tag @stefan-balke for commentary)

### PR DESCRIPTION
**Pull request by kyungyunlee**
#### Reference Issue
Fixes #728: "make smoothing optional in chroma_cens"

#### What does this implement/fix? Explain your changes.
Current chroma_cens assumes the smoothing as a default, but here, I added an option to not use smoothing at all. Also, allowing the user to choose the window function other than 'hann' window by adding a new parameter `smoothing_window='hann'`. 

#### Any other comments?
Regarding coverage, I see that it decreased a bit on the spectral features. I guess I should be adding the test for the `win_len_smooth=None`, but it looks like the baseline is from the chroma toolbox result (I see 3 `.mat` files with example parameters). Any tips on creating one like `'features-CT-CENS_None-1.mat'`? Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/766)

### CODE REVIEW

**Comment by lostanlen** [comment]
Thanks @kyungyunlee. It would be good to describe in short what sets aparts CENS from the conventional chroma representations, and how the smoothing comes into play, ideally with a reference to a specific equation or section in the Müller paper [1].
I'm sorry I can't help you right now with the test coverage.
(NB: I edited the OP to point to the reference issue #728)

**Comment by kyungyunlee** [comment]
@lostanlen Ah I see! Are you referring to adding some descriptions for documentation? I realized that currently there isn't much explanation about what CENS does in the doc.

**Comment by lostanlen** [comment]
Yes, it would be good to document CENS while we're at it. 
librosa implements three variants of chroma features and does not discuss the differences.
in particular, CENS is not part of the chroma tutorial: https://librosa.github.io/librosa/auto_examples/plot_chroma.html#sphx-glr-auto-examples-plot-chroma-py

**Comment by stefan-balke** [comment]
In short:
* L1-Normalization of each Chroma vector
* Quantization of the amplitudes to a "log-like" amplitude scale
* Smoothing with a sliding window
* (Downsampling–not in this implementation)

These features were designed mainly for retrieval application where timbre-invariance is a main ingredient.

**Comment by kyungyunlee** [comment]
@lostanlen Sure I will go through the referenced paper and add to both the doc and tutorial! 
@stefan-balke Thanks!!

**Comment by bmcfee** [comment]
It looks like the travis build is failing due to some numpy future warnings clogging up the log.  It's possible that we'll need to merge a future-proofing fix first before we can make progress on this issue-- sorry for that!

**Comment by bmcfee** [comment]
@kyungyunlee I just patched the travis config on master, and this should get us around the test failures that you're currently seeing.  You'll have to rebase this PR to the latest master to move this one forward.

**Comment by kyungyunlee** [comment]
@bmcfee Thank you for checking travis! The code for this issue itself is done, but I am actually trying to figure out how to add some stuff in the "enhanced chroma" tutorial as suggested by @lostanlen . I will let you know when I finish with that :)

**Comment by kyungyunlee** [comment]
I have added a "Chroma variants" section under the chroma tutorial and I would love some feedback (in fact, much needed I think...). 
Here is the gist of the `plot_chroma.py`, if it is more convenient to see the code right away :) 
[https://gist.github.com/kyungyunlee/e7f89bb7d897d09722c2d049524018a4](https://gist.github.com/kyungyunlee/e7f89bb7d897d09722c2d049524018a4) 
Thanks in advance!

**Comment by kyungyunlee** [comment]
I am not sure if my code review went through 😮 
Let me know if there is more to fix regarding the `chroma_cens` as well as the tutorial page!
Thanks :)

**Comment by bmcfee** [comment]
> Is the travis build resolved?

Not quite -- there's an open PR working toward fixing it, but there are actually a few things broken at this point.  I don't want to hold this one up while waiting for unrelated tests to get fixed though.

**Comment by bmcfee** [comment]
This looks great.  Thanks @kyungyunlee (and @lostanlen for CR)!  I guess this is merge-ready now?

**Comment by lostanlen** [comment]
:shipit: :shipit: :shipit:

**Comment by kyungyunlee** [comment]
Oh maybe I am late 😮 
Is there no need to modify the tutorial, as commented by @lostanlen ? 

Thanks!

**Comment by lostanlen** [comment]
@kyungyunlee yes, the ship has sailed. but that's ok: we can always merge your updated tutorial as part of a separate PR. the two improvements are relatively independent

**Comment by kyungyunlee** [comment]
😅😅oops, I will change some stuff and do it separately

**Pull request merged**
