### PR TITLE
Replaced the broken url for Sphinx and Matplotlib in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Abduttayyeb**
**Replaced the broken url links in CONTRIBUTING.md for** 
-Sphinx Webpage
-Matplotlib Webpage
on the line `117` and `118`

### CODE REVIEW

**Review by bmcfee — APPROVED** [review]
LGTM, thanks for catching these!

**Comment by bmcfee** [comment]
Is there anything else to add here, or are we good to merge?

**Comment by Abduttayyeb** [comment]
> Is there anything else to add here, or are we good to merge?

Yeaa sure, i can't find anything else to update in CONTRIBUTING.md

**Comment by bmcfee** [comment]
Great. Thanks again!

**Review by bmcfee — APPROVED** [review]

**Pull request merged**
