### PR TITLE
Adding python 3.12 to build matrix, update tests for recent scipy / numpy

### LINKED ISSUE #1772: Can Python 3.12 installation be supported
I try using`pip3.12 install librosa` is error，May I ask when we can support it
image

### PR DESCRIPTION
**Pull request by bmcfee**
#### Reference Issue

Fixes #1772 

#### What does this implement/fix? Explain your changes.

Adds 3.12 to supported versions, updates build matrix.

### CODE REVIEW

**Comment by bmcfee** [comment]
Fixed the failing nnls test and also a broken link in the intersphinx mapping.  This should be good to go when CI passes.

**Comment by bmcfee** [comment]
Now encountering a platform bug on osx (py3.12, numpy 1.26.4, scipy 1.12.0, numba 0.59.0) with multi-channel pyin. I'm not sure of the cause, though I expect it's down to differences in floating point operations.  The end result is that our centered multi-channel pyin test is failing due to a voicing estimation error.  The test passes on all other platforms / configs.

The most recent OSX passing build used py3.11, numpy 1.26.3, numba 0.58.1, and scipy 1.11.4.

Reading the release notes for the above, I don't see any obvious culprits.  I'll try to find some time to bisect this.

**Comment by bmcfee** [comment]
Regression is confirmed to be caused by scipy 1.12.0; 1.11.4 works.

**Comment by bmcfee** [comment]
Pretty baffled by this regression.  The only place we use scipy in this code path are in computing beta and boltzmann stats, and while the code for that has changed in 1.12.0, the outputs agree to numerical tolerance.

**Comment by bmcfee** [comment]
Ok, I'm going to need someone with access to a mac to help debug this one; bisecting through trial and error over GH actions will take forever.

From what I can tell, there are two places where we use scipy functionality in the pyin implementation:

https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/core/pitch.py#L816

and

https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/core/pitch.py#L903-L905

@richa-namballa verified that the beta distribution call is numerically equivalent from 1.11.4 to 1.12.0, so that leaves only the boltzmann call as the most likely source of the problem.  I've tried to dig through the compare log between scipy versions, and nothing jumped out at me as affecting boltzmann here, but it's possible that I missed something.

Could someone with a mac (@lostanlen ? @stefan-balke ?  @richa-namballa ?) take a crack at comparing boltzmann pmf outputs between 1.11.4 and 1.12.0 to see if something's gone wrong here?

**Comment by stefan-balke** [comment]
> Could someone with a mac (@lostanlen ? @stefan-balke ? @richa-namballa ?) take a crack at comparing boltzmann pmf outputs between 1.11.4 and 1.12.0 to see if something's gone wrong here?

Of course. Could you provide a meaningful call? The test case? Should I dump it as npz?

**Comment by bmcfee** [comment]
> Of course. Could you provide a meaningful call? The test case? Should I dump it as npz?

Thanks!  I actually have a hypothesis about what's going on now, see https://github.com/scipy/scipy/issues/20110#issuecomment-1953144749 .  I think what would be most helpful is if you can run the offending test on scipy 1.12.0 distributed on conda-forge (should fail) and then again on the pypi build, but with all other dependencies fixed.

**Comment by bmcfee** [comment]
@stefan-balke nevermind, I think we have this sorted out.  The problem was actually due to a divergence in libopenblas 0.3.26, not scipy.  I'm bypassing this test on OSX for now, but we can revisit later when openblas gets fixed.

This PR should be good to merge once CI passes.

**Comment by mattip** [comment]
> The problem was actually due to a divergence in libopenblas 0.3.26, not scipy. I'm bypassing this test on OSX for now, but we can revisit later when openblas gets fixed

Do you know what function(s) in OpenBLAS are in play? I think this can be checked by running the test under `ltrace` and using the `--library` option (the check can be done on linux).

**Comment by bmcfee** [comment]
> I think this can be checked by running the test under `ltrace` and using the `--library` option (the check can be done on linux).

I'm not getting any usable output from running this on my local machine (linux, conda-forge), but it's also possible that my build isn't using openblas at all.

I don't have an immediate guess for what's going on at the level of blas functions.  The triggering example is, as I mentioned previously, a pretty deep call stack and involves both numba/llvmlite and numpy vectorization.

Here's a gist of the test function isolated to a python script (ltracing pytest directly doesn't work): https://gist.github.com/bmcfee/b685d5234c4e111338c87c14323f2d56

This running on the current librosa main branch should do the job.  The conda environment spec in question is here: https://github.com/librosa/librosa/blob/main/.github/environment-ci.yml  - if you want to take a crack at tracing this directly, that environment and the above script should be enough to do it.

**Pull request merged**
