### PR TITLE
Dynamic tempo report with precision method

### PR DESCRIPTION
**Pull request by Willian-Zhang**
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/567)

### CODE REVIEW

**Comment by Willian-Zhang** [comment]
Please check #566 first

**Comment by Willian-Zhang** [comment]
What does this failure mean?
https://coveralls.io/builds/11307775/source?filename=librosa%2Fbeat.py#L480

**Comment by bmcfee** [comment]
> What does this failure mean?
> https://coveralls.io/builds/11307775/source?filename=librosa%2Fbeat.py#L480

It means that you've added code that is not covered by tests.

It also appears that the test build failed, so your changes seem to have caused librosa to behave incorrectly somehow.  Please look into the test report on travis.

**Comment by bmcfee** [comment]
Since this depends on #566, which has been closed, I'm closing this one out.  We can re-open in the future if the author follows the contributing guidelines.

**Pull request closed without merging**
