### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by stefan-balke**
Adressing issue #503

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/504)

### CODE REVIEW

**Comment by bmcfee** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 74 at r1](https://reviewable.io:443/reviews/librosa/librosa/504#-KcJU6igLd2kAHuNxz2C:-KcJU6igLd2kAHuNxz2D:b-ih9pl1) ([raw file](https://github.com/librosa/librosa/blob/6fb09ccd9dd3fe4eec3e5302018291366a9f885d/README.md#L74)):*
> ```Markdown
> or *GStreamer*. (If you are using the conda package for
> `audioread`, *ffmpeg* will be installed automatically.)
> ```

is audioread in the main conda dist, or do you have to use conda-forge?

If the latter, give an explicit cmdline:

```
conda install -c conda-forge ffmpeg
```

audioread also needs pygobject to work with gstreamer, so that should be listed as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/504)*

**Comment by stefan-balke** [comment]
*[README.md, line 74 at r1](https://reviewable.io:443/reviews/librosa/librosa/504#-KcJU6igLd2kAHuNxz2C:-KcYndtyREyrZE8W9Jgp:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/6fb09ccd9dd3fe4eec3e5302018291366a9f885d/README.md#L74)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

is audioread in the main conda dist, or do you have to use conda-forge?

If the latter, give an explicit cmdline:

```
conda install -c conda-forge ffmpeg
```

audioread also needs pygobject to work with gstreamer, so that should be listed as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/504)*

**Comment by stefan-balke** [comment]
So I think we cannot give complete instructions but I think this gives enough hints that users will solve it by doing some googling....

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/504)*

**Comment by bmcfee** [comment]
> these would only work on debian/ubuntu based systems

That's true ; we could throw in a yum line for completeness.  Past that, if a user's on linux and not on a yum/apt-based system, odds are they can figure it out themselves anyway.

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/504)*

**Comment by bmcfee** [comment]
LGTM, what do you think @faroit ?

**Comment by faroit** [comment]
> LGTM, what do you think @faroit ?
👍

**Pull request merged**
