### PR TITLE
fix peak_pick util func doc

### PR DESCRIPTION
**Pull request by changgunyee**
#### What does this implement/fix? Explain your changes.
fix documentation of util.peak_pick func.
Since `n` is the length of `x` rows, it is a little bit confusing.

### CODE REVIEW

**Comment by lostanlen** [comment]
i'm not sure that this is truly needed. `n` is clearly defined above.

**Comment by bmcfee** [comment]
Thanks @changgunyee for opening this PR.  I do agree with @lostanlen in this case, all terms are clearly defined in the context of the docstring, and I think it's clearer to refer explicitly to `n` here.

Maybe someone else a little less close to the code can chime in though?

**Comment by changgunyee** [comment]
I thought there's two `n`. One in the description part for `x[n]` and the other in params for x's shape `shape=[n,]`. And it was confusing for me.

But it's like other people weren't, I will close this PR.

Thanks for CR.

**Comment by lostanlen** [comment]
ah, yes. Good point. I would be in favor of changing the shape to a different letter, like `N` for example. But perhaps it's not necessary to define a math variable for it at all. We just need to convey the idea that it's a 1-D time series. It's best to remain consistent across the library.

**Comment by changgunyee** [comment]
I read most of the documentation and it seems changing `n` in description part to `i` looks good as other function docstrings usually use `i` as index for loop and `n` for 1-D time series.

Is there another suggestion?

**Comment by lostanlen** [comment]
looks good to me

**Comment by changgunyee** [comment]
Thanks for review. I'll close this since this is not significant PR.

**Comment by bmcfee** [comment]
Thanks for your effort on this anyway, @changgunyee !

**Pull request closed without merging**
