### PR TITLE
Precise onset

### PR DESCRIPTION
**Pull request by Willian-Zhang**
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/566)

### CODE REVIEW

**Comment by bmcfee** [comment]
Please fill out the pull request template form, and explain what problem this change is meant to fix, and how it works.

Thanks!

**Comment by bmcfee** [comment]
@Willian-Zhang can you please fill out the PR template and document what this change is meant to address?  If not, I'll have to close this out.  Thanks.

**Comment by bmcfee** [comment]
Since the author has not followed our contributing guidelines, I'm closing this one out.  We can re-open in the future if the requested documentation is provided.

**Comment by Willian-Zhang** [comment]
@bmcfee I'm heading back to this PR and working on filling the PR template, sry for the late reply.

**Pull request closed without merging**
