### PR TITLE
[MRG] Discard phase before amplitude_to_db in docs + update warning in *_to_db

### LINKED ISSUE #723: Tutorials and docs call amplitude_to_db and power_to_db with complex inputs
#### Description
Since PR #671 (which closed issue #662), the example code for `specshow` uses `librosa.amplitude_to_db` on the output of `stft`, which raises a `UserWarning` in the absence of a `magphase` transformation.
Searching for `amplitude_to_db` reveals other example codes where the same situation happens: `plot_hprss`, `plot_segmentation`, `segment.py` docstring, `constantq.py` docstring.

#### Steps/Code to Reproduce
copy-pasting example from specshow docs
```
import matplotlib.pyplot as plt
y, sr = librosa.load(librosa.util.example_audio_file())
plt.figure(figsize=(12, 8))

D = librosa.amplitude_to_db(librosa.stft(y), ref=np.max)
plt.subplot(4, 2, 1)
librosa.display.specshow(D, y_axis='linear')
plt.colorbar(format='%+2.0f dB')
plt.title('Linear-frequency power spectrogram')

```

#### Expected Results
no warning :)

#### Actual Results
```
~/miniconda3/lib/python3.6/site-packages/librosa/core/spectrum.py:959: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(magphase(D)[0]) instead.
  warnings.warn('amplitude_to_db was called on complex input so phase '
```

#### Versions
```
Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.13.1
SciPy 0.19.1
librosa 0.6.1rc0
```

### PR DESCRIPTION
**Pull request by lostanlen**
#### Reference Issue
Fixes #723.
Since PR #671 (which closed issue #662), the example code for specshow uses librosa.amplitude_to_db on the output of stft, which raises a UserWarning in the absence of a magphase transformation.
Searching for _to_db( reveals the same problem in over 20 example codes, in tutorial notebooks, and docstring.

#### What does this implement/fix? Explain your changes.
As an example, the previous docstring for STFT was:
```
>>> librosa.display.specshow(librosa.power_to_db(D), y_axis='log', x_axis='time')
```

This PR replaces the above with the following:
```
>>> D_dB = librosa.power_to_db(np.abs(D)**2, ref=np.max)
>>> librosa.display.specshow(D_dB, y_axis='log', x_axis='time')
```

#### Any other comments?
I had previously submitted PR #742 to fix the same issue, but during the review process @bmcfee and I realized that it would be simpler, and therefore better, to just use `np.abs` rather than `librosa.magphase()` when possible.

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/751)

### CODE REVIEW

**Comment by stefan-balke** [comment]
___
*[librosa/core/spectrum.py, line 1041 at r1](https://reviewable.io/reviews/librosa/librosa/751#-LIGL0DU7o4XfOQ6Vr5B:-LIGL0DV2_rOsvpXbCG2:bi0t0qs) ([raw file](https://github.com/librosa/librosa/blob/18083a73acd6a351b98da6a2830ff9a589d05f98/librosa/core/spectrum.py#L1041)):*
> ```Python
> 
>     >>> y, sr = librosa.load(librosa.util.example_audio_file())
>     >>> CQT = librosa.cqt(y, sr=sr, fmin=librosa.note_to_hz('A1'))
> ```

To align this to the other examples, we should use `C`, rather then `CQT`, or?

**Comment by stefan-balke** [comment]
___
*[librosa/util/utils.py, line 1308 at r1](https://reviewable.io/reviews/librosa/librosa/751#-LIGLAnb-PJBoJKbpsM5:-LIGLAnb-PJBoJKbpsM6:b-fehvv5) ([raw file](https://github.com/librosa/librosa/blob/b63698ffd43d5e91171ef522d69a45deb302eb76/librosa/util/utils.py#L1308)):*
> ```Python
>     >>> y, sr = librosa.load(librosa.util.example_audio_file())
>     >>> tempo, beats = librosa.beat.beat_track(y=y, sr=sr, trim=False)
>     >>> cqt = np.abs(librosa.cqt(y=y, sr=sr))
> ```

Here the same as above

**Comment by stefan-balke** [comment]
___
*[librosa/core/spectrum.py, line 105 at r1](https://reviewable.io/reviews/librosa/librosa/751#-LIGLFhp7VOwubEv9Y-y:-LIGLFhp7VOwubEv9Y-z:bg3a0py) ([raw file](https://github.com/librosa/librosa/blob/b63698ffd43d5e91171ef522d69a45deb302eb76/librosa/core/spectrum.py#L105)):*
> ```Python
> 
>     >>> y, sr = librosa.load(librosa.util.example_audio_file())
>     >>> D = np.abs(librosa.stft(y))
> ```

This looks weird to me, shouldn't we do `D = librosa.stft(y)` and then in a new line `D = np.abs(D)` for the sake of clarity? Holds true for all changes and up for discussion.

**Comment by stefan-balke** [comment]
___
*[librosa/core/spectrum.py, line 107 at r1](https://reviewable.io/reviews/librosa/librosa/751#-LIGLklm7AdiVs8ouxKY:-LIGLklm7AdiVs8ouxKZ:bjt8565) ([raw file](https://github.com/librosa/librosa/blob/b63698ffd43d5e91171ef522d69a45deb302eb76/librosa/core/spectrum.py#L107)):*
> ```Python
>     >>> D = np.abs(librosa.stft(y))
>     >>> D
>     array([[  2.576e-03 -0.000e+00j,   4.327e-02 -0.000e+00j, ...,
> ```

Why is this still a complex `dtype`?

**Comment by stefan-balke** [comment]
@lostanlen thanks for this update and in general this is super. Just have a more style-related question in the review. Would be fine with any solution.

**Comment by lostanlen** [comment]
@stefan-balke my round of revisions is complete. Thanks again for the CR. I incorporated the changes in naming conventions and updated the numerical output in the `stft` docstring

That said, I'm not sold on what you argued earlier:
> shouldn't we do D = librosa.stft(y) and then in a new line D = np.abs(D) for the sake of clarity?

so I'm leaving this part on hold.

**Comment by stefan-balke** [comment]
:lgtm:

**Comment by lostanlen** [comment]
Thanks again @stefan-balke for the CR. This is ready for merging. On to librosa v0.6.2!

**Comment by bmcfee** [comment]
Thanks @lostanlen and @stefan-balke !

**Pull request merged**
