### PR TITLE
Modified random fake audio generation

### PR DESCRIPTION
**Pull request by siddhugolu**
Fixes [#635](https://github.com/librosa/librosa/issues/635).
Modified random audio generation to restrict it to the range of [-1, 1]. Changed data -> audio

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/637)

### CODE REVIEW

**Comment by bmcfee** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/ioformats.rst, line 124 at r1](https://reviewable.io:443/reviews/librosa/librosa/637#-Kwj8IUd9-vPFZZZsh9I:-Kwj8IUd9-vPFZZZsh9J:b-tnvi09) ([raw file](https://github.com/librosa/librosa/blob/d3ad343b82e633bdbf22151487f4faa0b9dfbd2f/docs/ioformats.rst#L124)):*
> ```reStructuredText
> 
>     rate = 44100
>     data = np.random.randn(rate * 10, 2)
> ```

Could you also change it here as well, for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/637)*

**Comment by bmcfee** [comment]
@siddhugolu thanks for doing this!  I had one minor comment, but it looks good otherwise.

@faroit You wrote this one originally -- does this look okay to you?  Is there anything else that should be changed?

**Comment by siddhugolu** [comment]
@bmcfee done!

**Comment by faroit** [comment]
@siddhugolu @bmcfee looks good to me

**Comment by bmcfee** [comment]
:lgtm: thanks @siddhugolu and @faroit !

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/637#-:-Kwj_AsoOwI2kAbyn48m:b-s7nfd)*

**Pull request merged**
