### PR TITLE
change mode --> pad_mode in docstrings

### PR DESCRIPTION
**Pull request by keunwoochoi**
#### What does this implement/fix? Explain your changes.

Update 'mode' to 'pad_mode' in the docstrings of `STFT` and `ifgram`.

#### Any other comments?

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/684)

### CODE REVIEW

**Comment by bmcfee** [comment]
Is this just a docstring change?  Did we at some point rename the parameters and forget to update the docstrings?

**Comment by keunwoochoi** [comment]
Yes, and yes I doubt so. If it’s more convenient to fix it in your working branch please go ahead!

On 1Mar 2018, at 17:11, Brian McFee <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this just a docstring change? Did we at some point rename the parameters and forget to update the docstrings?

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/684)*

**Comment by bmcfee** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/684#-:-L6XpDyrQPu_3_eiVB0O:bnfp4nl)*

**Comment by bmcfee** [comment]
Anything else to add, or is this good to merge?

**Comment by keunwoochoi** [comment]
There’s nothing else although I wanted to find something more ;) it’s good to go.

On 1 Mar 2018, at 19:57, Brian McFee <notifications@github.com<mailto:notifications@github.com>> wrote:


Anything else to add, or is this good to merge?

**Comment by bmcfee** [comment]
Awesome.  Thanks!  :shipit:

**Pull request merged**
