### PR TITLE
add `power` keyword argument

### PR DESCRIPTION
**Pull request by keunwoochoi**
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/472)

### CODE REVIEW

**Comment by bmcfee** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/feature/spectral.py, line 1280 at r1](https://reviewable.io:443/reviews/librosa/librosa/472#-KYdabMFo5QMZ3MNpGIT:-KYdabMG1hqVK7QGQSZI:b-4xzi9t) ([raw file](https://github.com/librosa/librosa/blob/77d7d841d27e8025019b711f38e5b52ad0e2daef/librosa/feature/spectral.py#L1280)):*
> ```Python
>                    power=2.0, **kwargs):
>     """Compute a Mel-scaled spectrogram.
>     By default, it returns power-spectrogram (`power=2.0`).
> ```

Could you expand this explanation to say that power is computed before mel filtering?

Also that power is ignored if S is provided.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/472)*

**Comment by keunwoochoi** [comment]
How's it now? By the way I haven't used reviewable so just commenting here.

**Comment by bmcfee** [comment]
NP.  Looks good, though I'll probably expand it in the docstring audit #419 .

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/472#-:-KYeIkduPNq9oS3FWuSE:bqzngv6)*

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/472)*

**Pull request merged**
