### PR TITLE
Data loader / more example tracks

### LINKED ISSUE #952: RFC: more example tracks?
It's been mentioned on numerous occasions that our current example track, catchy as it may be, is not great for demonstrating many of the functions of librosa.  In offline discussions, @lostanlen and I have talked about extending the included audio content to have several tracks, which could be used to demonstrate different functionality.  So I want to kick this out to the community: what do you want to see in our examples?  By this I mean: please recommend specific recordings.

To prevent this discussion from becoming an infinite bike shed, I'm going to lay down some ground rules for inclusion:

1. Content must be CC-licensed or public domain.
2. Total content should not bloat the package too much; I think 10MB is a reasonable upper bound, and this functionally limits us to between 5 and 10 total recordings.
3. No single track should be too long.  It's okay to have some very short examples.
4. The total collection should be diverse in terms of style, instrumentation, polyphony, etc.  If possible, I'd like to include some non-western recordings as well.
5. Any lyrical content should not be offensive, for some reasonable definition of offensive which is compatible with our [CoC](https://github.com/librosa/librosa/blob/master/CODE_OF_CONDUCT.md).  I don't expect any problems here, but I'll reserve executive privilege here to veto anything that could be problematic.
6. Familiarity would be a bonus, for making the examples and documentation more immediately accessible.

With all of that out of the way, let's talk about things not currently demonstrated by our current example.  We don't have to hit all of these, and I'm sure I'm missing some, but we should aim to hit most of them.

* Monophonic audio: we should have at least one solo instrument recording that can be used to demonstrate things like pitch tracking.  Maybe a raga or makam could be good here?  This could also be good for demonstrating onsets.
* Interesting harmony: the current example is pretty boring, harmonically speaking.  Maybe a jazz recording would be appropriate here?  Maybe something with some key changes as well.
* Non-percussive rhythmic elements: something classical (strings) would be nice to have for demonstrating onset and beat tracking with soft attacks.
* Different time signatures: examples with 4/4, 3/4, and maybe a 5/4 or 7/8 would be nice for demonstrating some of the rhythmic features (tempogram, fmt)
* Vocals and instrumentals: we should have at least one track with vocals.
* Non-musical audio: do we need/want this?  Speech?  Environmental sound?  Librosa gets used for these things, so it might be worth considering their inclusion.

Some other discussions that we can have around this:

- Should we have a multi-track / stem set as one of the examples?
- What kind of genre coverage should we strive for?
- How does this issue interact with #641 (non-western systems in display)?  Is #641 a pre-requisite for including non-western examples?  (I'd argue that it should be, and that this would be a good motivating factor for finally doing it.)

Finally, the examples gallery already includes a few candidate options [here](https://github.com/librosa/librosa/tree/master/docs/examples/audio).  We can take some, all, or none of these, but whatever we decide on including should serve as plausible replacements for them and the example notebooks should be revised afterward.

### PR DESCRIPTION
**Pull request by bmcfee**
#### Reference Issue
Fixes #952 

#### What does this implement/fix? Explain your changes.

This PR replaces our single pre-packaged example audio clip by a collection maintained at https://github.com/librosa/librosa-data .

It uses `pooch` to handle remote file access and caching, and provides a couple of helpers to expose the available data to users.

Shortcuts `librosa.example` and `librosa.ex` are provided to make things easy to use.

The old example file is included in the new collection, and can be accessed by `librosa.ex('vibeace')`.  A deprecation shim is in place until 0.9 to preserve the old API.

#### Any other comments?

TBD:

- [x] cache the cache on appveyor
- [x] tests
- [x] improve documentation on how to control the cache location
- [x] audit the documentation to use more appropriate examples for each function
- [x] add more tracks to the mixtape (see #952 ) 
- ~[ ] migrate direct github downloads to an archived zenodo link~

### CODE REVIEW

**Comment by bmcfee** [comment]
## How to use this

The old style:
```python
>>> fname = librosa.util.example_audio_file()
>>> y, sr = librosa.load(fname)
```
The new style:
```python
# Already downsampled to 22KHz mono
>>> y, sr = librosa.load(lbrosa.ex('vibeace'))

# Original quality
>>> y, sr = librosa.load(lbrosa.ex('vibeace', hq=True))
```

List the examples (so far):
```python
>>> librosa.util.list_examples()
AVAILABLE EXAMPLES
--------------------------------------------------------------------
brahms    	Brahms - Hungarian Dance #5
choice    	Admiral Bob - Choice (drum+bass)
nutcracker	Tchaikovsky - Dance of the Sugar Plum Fairy
vibeace   	Kevin MacLeod - Vibe Ace
waller    	Fats Waller - Ain't Misbehavin'
```

**Comment by bmcfee** [comment]
I think this is basically feature complete and ready for cr.

Merge should eat until we finalize the track list and set up zenodo storage

**Comment by bmcfee** [comment]
A couple more points of discussion here:

1. Should we set up the data files as a subtree to the `librosa-data` repo, so that they're always in sync (in dev anyway)?
2. Should we have the source url pull from github when `'dev' in librosa.__version__` and zenodo when on a stable release?

**Comment by bmcfee** [comment]
> * Should we set up the data files as a subtree to the `librosa-data` repo, so that they're always in sync (in dev anyway)?
> 

I looked into this, and I think it will be more of a hassle than it's worth.  These data files shouldn't change too often.

> * Should we have the source url pull from github when `'dev' in librosa.__version__` and zenodo when on a stable release?

For this, I think we should use the `packaging` library's tools for [version parsing](https://packaging.pypa.io/en/latest/version/), and propose the following logic:

1. `v.is_prerelease and (v.pre is None)` ==> github   (example: `0.8.0.dev`)
2. `v.is_prerelease and (v.pre is not None)` ==> zenodo  (example: `0.8.0rc0`)
2. `not v.is_prerelease` ==> zenodo  (example: `0.8.0`)

**Comment by bmcfee** [comment]
Relying on zenodo integration seems like a bit more of a hassle than I was hoping.

Instead, I've set up a direct URL for accessing the data at https://librosa.org/data/ ; if we ever want to migrate off github, the link should continue to work.

I think this is :shipit: once CI passes.  Anyone else want to chime in?

**Comment by bmcfee** [comment]
Side note: I think we're good (for now) on example tracks.  The additional content that I'd like to add can be rolled into #641 when the time comes.

**Comment by lostanlen** [comment]
@bmcfee i don't understand the nomenclature of track IDs. Is there a reason why the Hungarian Dance #5 gets labeled by its composer (`brahms`) but the Tchaikovsky piece by its title (`nutcracker`)? The list of tracks is very short, so i can live with the inconsistency; but i'm concerned that it would be worth to document why these tracks were chosen in the librosa "mixtape". Do they reflect a specific genre or instrumentation? Are they fit for a specific MIR task? At the moment, it's impossible to know without listening to all samples.

**Comment by bmcfee** [comment]
> @bmcfee i don't understand the nomenclature of track IDs. Is there a reason why the Hungarian Dance #5 gets labeled by its composer (`brahms`) but the Tchaikovsky piece by its title (`nutcracker`)?

Yeah, because there isn't one :shrug: I was mainly aiming for salience and brevity.



> The list of tracks is very short, so i can live with the inconsistency; but i'm concerned that it would be worth to document why these tracks were chosen in the librosa "mixtape".

A fair point.  I'm not sure where would make sense to document this stuff though.  Maybe a blog post?  Or in the README for the data repo?

**Comment by lostanlen** [comment]
Yes, I think that it would be good to add to the README a one-sentence description of the track, describing its content + the reason why it was added

Another thing which is frustrating is that there isn't a programmatic way to list examples. The `list_examples` function prints the list, but doesn't return it. I have only read the PR superficially, but it seems like the only way to list the example keys is to access a relatively obscure global variable: `librosa.files.__TRACKMAP.keys()`

**Comment by bmcfee** [comment]
> Another thing which is frustrating is that there isn't a programmatic way to list examples. The `list_examples` function prints the list, but doesn't return it.

That's right.  I thought about adding this, but couldn't construct a plausible use-case for it.  The examples here are primarily meant to serve the documentation, and I want to encourage users to be deliberate about choosing example tracks rather than brute-forcing through all of them for some reason.  But maybe you have a different use-case in mind?

**Comment by bmcfee** [comment]
> Yes, I think that it would be good to add to the README a one-sentence description of the track, describing its content + the reason why it was added. Even better if that description can be pulled directly from librosa. "Vibe Ace" and "Choice" aren't informative per se.

Hrm.  Maybe a page in the documentation would be appropriate then.  Off the top of my head, here's how I've been thinking about them:

- vibe ace : backward compatibility
- fishin : good for demonstrating structure / segmentation
- choice : hpss
- brahms : variable tempo (eg for tempogram and plp), soft onsets
- nutcracker : fixed tempo, harmony
- trumpet : monophonic

**Comment by bmcfee** [comment]
> Maybe a page in the documentation would be appropriate then.

Done.

**Comment by lostanlen** [comment]
Wonderful! Many thanks for addressing this so fast. Makes a lot of sense now.

**Comment by bmcfee** [comment]
Ok, docstrings are now up to date for constantq.py, which finishes up the purging of `example_audio_file` from our example code.

Once CI finishes, I think this is good to go.

**Pull request merged**
