### PR TITLE
0.6.3 release preparation

### PR DESCRIPTION
**Pull request by bmcfee**
#### What does this implement/fix? Explain your changes.

This PR updates documentation, versions, and other dangling small issues ahead of the 0.6.3 release.

It is work in progress until all tagged issues are completed, but I'm hoping to push this out before 2019.

#### Any other comments?

@nullmightybofo and @toddrme2178: how would you like to be attributed in the changelog / contributors list?

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/809)

### CODE REVIEW

**Comment by bmcfee** [comment]
Trying once more:

@nullmightybofo and @toddrme2178: how would you like to be attributed in the changelog / contributors list?

**Comment by Robrib** [comment]
You mean what kind of contributor? I don’t know, maybe anyone you think is proper.

Yours,
Ma

在 2019年1月31日，上午9:26，Brian McFee <notifications@github.com<mailto:notifications@github.com>> 写道：


@Robrib<https://github.com/Robrib> how would you like to be attributed in the contributors list for this release?

**Comment by bmcfee** [comment]
> Can I just go as nullmightybofo?

@nullmightybofo Yup, that's totally fine!


> You mean what kind of contributor? I don’t know, maybe anyone you think is proper.

@Robrib no, I mean your name in the changelog -- since you and @monsij submitted nearly identical pull requests, but I could only accept one, I'd like to give credit to both.  If you just want your github handle, that's fine too.

**Comment by bmcfee** [comment]
@toddrme2178 hasn't responded, but I think we've waiting long enough and can ship this anyway.  We can always revise docs later if he decides to chime in on attribution.

I'll merge this and :shipit: for 0.6.3

**Pull request merged**
