### PR TITLE
add license title

### PR DESCRIPTION
**Pull request by waldyrious**
It's not strictly required, but it's useful metadata, and part of the recommended license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license)

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/382)

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks!

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/382)*

**Comment by waldyrious** [comment]
@bmcfee would you mind if I sent similar PRs to muda and resampy, or would you rather edit the license files directly yourself? I don't want to spam :)

**Comment by bmcfee** [comment]
> I don't want to spam

no problem, spam away!

**Comment by waldyrious** [comment]
Ok then! Expect some activity soon :)

**Pull request merged**
