### PR TITLE
Tightened requirements on valid_audio

### LINKED ISSUE #1122: waveplot() segfaults when given input of shape (1, 35000)
#### Description
When waveplot() is given a numpy array of shape (1, 35000), the interpreter segfaults.

#### Steps/Code to Reproduce
```
$ python
Python 3.7.6 (default, Feb  8 2020, 13:20:58) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from librosa.display import waveplot
/home/sliedes/.virtualenvs/torch/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/home/sliedes/.virtualenvs/torch/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
>>> import numpy as np
>>> waveplot(np.zeros((1, 35000)))
Segmentation fault (core dumped)
```

#### Expected Results
waveplot fails gracefully, at least does not crash the interpreter.

#### Actual Results
Python interpreter segfaults.

#### Versions
Linux-5.6.7-arch1-1-x86_64-with-arch
Python 3.7.6 (default, Feb  8 2020, 13:20:58) 
[GCC 9.2.0]
NumPy 1.17.3
SciPy 1.2.0
librosa 0.7.2

### PR DESCRIPTION
**Pull request by bmcfee**
#### Reference Issue
Fixes #1122 

#### What does this implement/fix? Explain your changes.

This PR fixes / prevents #1122 by tightening the constraints on `valid_audio`.

Monophonic data must be of shape `(N,)`, multichannel data cannot have shape `(1, N)`. (Only 2 and above are allowed.)

#### Any other comments?

This should be revised when we implement #1130

### CODE REVIEW

**Comment by bmcfee** [comment]
NB: Appveyor test fails are due to an old API key, and not indicative of real failures.

**Comment by bmcfee** [comment]
Confirmed offline that this addresses the original waveplot issue #1122 .  I think this is good to go-- anyone care to look it over?

**Comment by lostanlen** [comment]
unrelated, but: why is `valid_audio` cached? is it really faster?

**Comment by bmcfee** [comment]
Any objections to merging this one?

**Comment by lostanlen** [comment]
> It's O(N) in the "worst" case (valid audio) due to the isfinite check. It's cached because it may be called many times for the same audio in a processing pipeline.

Thanks for explaining. I was initially worried about the overhead of storing `y` in memory and comparing it to new inputs every time the function is called; but i had forgotten that librosa's cache was joblib-based (as opposed to memoized). So IIUC it caches by looking up a hash table, which is a small price to pay in comparison with `O(len(y))`.

LGTM

**Pull request merged**
