### PR TITLE
Trimming should work for zero-only signals as well

### LINKED ISSUE #645: Error when trimming an array containing only zeros
#### Description
Error when trimming an array containing only zeros

#### Steps/Code to Reproduce
    import librosa
    librosa.effects.trim(np.zeros(1), ref=1)

#### Expected Results
Should return an empty array and range of length zero.

#### Actual Results
    Traceback (most recent call last):
        ...
        librosa.effects.trim(np.zeros(1), ref=1)
      File ".../python3.6/site-packages/librosa/effects.py", line 478, in trim
        start = int(core.frames_to_samples(nonzero[0], hop_length))
    IndexError: index 0 is out of bounds for axis 0 with size 0

#### Versions
Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
NumPy 1.13.3
SciPy 1.0.0
librosa 0.5.1

### PR DESCRIPTION
**Pull request by naktinis**
#### Reference Issue
Fixes #645 

#### What does this implement/fix? Explain your changes.
Special handling of start and end position calculation for zero-only signals

#### Any other comments?
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/646)

### CODE REVIEW

**Comment by bmcfee** [comment]
Oops, nevermind my comment at #645, you're way ahead of me!

Could you add a unit test to verify that the fix behaves as expected?

**Comment by bmcfee** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/646#-:-L-7QFT_QuSg_PqRJbPo:bnfp4nl)*

**Comment by bmcfee** [comment]
Thanks @naktinis for this!  Is there anything else you'd like to add, or shall we merge?

**Comment by naktinis** [comment]
@bmcfee merging is fine with me

**Pull request merged**
