### PR TITLE
Call magphase before power_to_db and amplitude_to_db in docs

### LINKED ISSUE #723: Tutorials and docs call amplitude_to_db and power_to_db with complex inputs
#### Description
Since PR #671 (which closed issue #662), the example code for `specshow` uses `librosa.amplitude_to_db` on the output of `stft`, which raises a `UserWarning` in the absence of a `magphase` transformation.
Searching for `amplitude_to_db` reveals other example codes where the same situation happens: `plot_hprss`, `plot_segmentation`, `segment.py` docstring, `constantq.py` docstring.

#### Steps/Code to Reproduce
copy-pasting example from specshow docs
```
import matplotlib.pyplot as plt
y, sr = librosa.load(librosa.util.example_audio_file())
plt.figure(figsize=(12, 8))

D = librosa.amplitude_to_db(librosa.stft(y), ref=np.max)
plt.subplot(4, 2, 1)
librosa.display.specshow(D, y_axis='linear')
plt.colorbar(format='%+2.0f dB')
plt.title('Linear-frequency power spectrogram')

```

#### Expected Results
no warning :)

#### Actual Results
```
~/miniconda3/lib/python3.6/site-packages/librosa/core/spectrum.py:959: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(magphase(D)[0]) instead.
  warnings.warn('amplitude_to_db was called on complex input so phase '
```

#### Versions
```
Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.13.1
SciPy 0.19.1
librosa 0.6.1rc0
```

### PR DESCRIPTION
**Pull request by lostanlen**
#### Reference Issue
Fixes #723.

Since PR #671 (which closed issue #662), the example code for `specshow` uses `librosa.amplitude_to_db` on the output of `stft`, which raises a `UserWarning` in the absence of a `magphase` transformation.
Searching for `_to_db(` reveals the same problem in over 20 example codes, in tutorial notebooks, and docstring.

#### What does this implement/fix? Explain your changes.
As an example, the previous docstring for STFT was:
```
    >>> librosa.display.specshow(librosa.power_to_db(D), y_axis='log', x_axis='time')
```

This PR replaces the above with the following:
```
    >>> D_dB = librosa.power_to_db(librosa.magphase(D, power=2)[0], ref=np.max)
    >>> librosa.display.specshow(D_dB, y_axis='log', x_axis='time')
```

#### Any other comments?
After an offline discussion with @bmcfee, I decided to consistently use `np.abs(D)` instead of `librosa.magphase(D)[0]` for getting the amplitude when the phase is not necessary as a future step. However, I consistently use `librosa.magphase(D, power=2)[0]` instead of `np.abs(D)**2`. I reflected this convention in the warning messages of `power_to_db` and `amplitude_to_db`.

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/742)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 3 of 13 files at r1.
Review status: 3 of 13 files reviewed, 2 unresolved discussions (waiting on @lostanlen)

---

*[docs/examples/plot_presets.py, line 65 at r1](https://reviewable.io/reviews/librosa/librosa/742#-LG75fgg0U-NI96OVJ1l:-LG75fgg0U-NI96OVJ1m:bf5zais) ([raw file](https://github.com/librosa/librosa/blob/65368f0cecd0e22df980ba4d72a52386be4c62a9/docs/examples/plot_presets.py#L65)):*
> ```Python
> 
> # Generate a complex-valued mel spectrogram:
> M = librosa.feature.melspectrogram(y=y)
> ```

melspectrogram does not produce complex values

---

*[docs/examples/plot_segmentation.py, line 50 at r1](https://reviewable.io/reviews/librosa/librosa/742#-LG75qpc1ZgTOfyUz6iS:-LG75qpc1ZgTOfyUz6iT:bf4nxyf) ([raw file](https://github.com/librosa/librosa/blob/65368f0cecd0e22df980ba4d72a52386be4c62a9/docs/examples/plot_segmentation.py#L50)):*
> ```Python
>                 n_bins=N_OCTAVES * BINS_PER_OCTAVE),
>     ref=np.max)
> C_dB = librosa.power_to_db(librosa.magphase(C, power=2)[0])
> ```

Any reason to use `power=2` and `power_to_db` instead of `abs` and `amplitude_to_db`? (Here and elsewhere)

---


*Comments from [Reviewable](https://reviewable.io/reviews/librosa/librosa/742)*

**Comment by bmcfee** [comment]
Thanks @lostanlen for doing this!  The one thing that I don't get here is the use of intermediate power calculations and `power_to_db`, rather than `amplitude_to_db` with `abs`?  I would expect the latter to be used unless power is needed for other purposes.

**Comment by lostanlen** [comment]
Thank you for your CR.
The day we want to accelerate `magphase(z, power=2)`, we can write a numba-vectorized `abs2` function that does not need the square root:

```
@numba.vectorize([numba.float64(numba.complex128),numba.float32(numba.complex64)])
def abs2(x):
    return x.real*x.real + x.imag*x.imag
```

This is why I encouraged `magphase` for `power_to_db`, but relied on the built-in `np.abs` for `amplitude_to_db`

**Comment by lostanlen** [comment]
Review status: 3 of 13 files reviewed, 2 unresolved discussions (waiting on @bmcfee and @lostanlen)

---

*[docs/examples/plot_presets.py, line 65 at r1](https://reviewable.io/reviews/librosa/librosa/742#-LG75fgg0U-NI96OVJ1l:-LG7KnOLC96xGyWRILNp:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/65368f0cecd0e22df980ba4d72a52386be4c62a9/docs/examples/plot_presets.py#L65)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

melspectrogram does not produce complex values
</blockquote></details>

Done.

---

*[docs/examples/plot_segmentation.py, line 50 at r1](https://reviewable.io/reviews/librosa/librosa/742#-LG75qpc1ZgTOfyUz6iS:-LG7KwiR3a-jNzmPoOfT:b-t69zwt) ([raw file](https://github.com/librosa/librosa/blob/65368f0cecd0e22df980ba4d72a52386be4c62a9/docs/examples/plot_segmentation.py#L50)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Any reason to use `power=2` and `power_to_db` instead of `abs` and `amplitude_to_db`? (Here and elsewhere)
</blockquote></details>

The day we want to accelerate `magphase(z, power=2)`, we can write a numba-vectorized `abs2` function that does not need the square root:

```
@numba.vectorize([numba.float64(numba.complex128),numba.float32(numba.complex64)])
def abs2(x):
    return x.real*x.real + x.imag*x.imag
```

This is why I encouraged `magphase` for `power_to_db`, but relied on the built-in `np.abs` for `amplitude_to_db`

---


*Comments from [Reviewable](https://reviewable.io/reviews/librosa/librosa/742)*

**Comment by lostanlen** [comment]
Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @bmcfee)

---



*Comments from [Reviewable](https://reviewable.io/reviews/librosa/librosa/742)*

**Comment by bmcfee** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @bmcfee)

---

*[docs/examples/plot_segmentation.py, line 50 at r1](https://reviewable.io/reviews/librosa/librosa/742#-LG75qpc1ZgTOfyUz6iS:-LG7eI_uDlYvUnXr8MNH:bonf8k6) ([raw file](https://github.com/librosa/librosa/blob/65368f0cecd0e22df980ba4d72a52386be4c62a9/docs/examples/plot_segmentation.py#L50)):*
<details><summary><i>Previously, lostanlen (Vincent Lostanlen) wrote…</i></summary><blockquote>

The day we want to accelerate `magphase(z, power=2)`, we can write a numba-vectorized `abs2` function that does not need the square root:

```
@numba.vectorize([numba.float64(numba.complex128),numba.float32(numba.complex64)])
def abs2(x):
    return x.real*x.real + x.imag*x.imag
```

This is why I encouraged `magphase` for `power_to_db`, but relied on the built-in `np.abs` for `amplitude_to_db`
</blockquote></details>

But np.abs is compiled code and runs in place, so it will be faster and more memory efficient.

---


*Comments from [Reviewable](https://reviewable.io/reviews/librosa/librosa/742)*

**Comment by bmcfee** [comment]
I like option b. Docs can always be changed, and I don't want new functionality to hold up the 0.6.2 release.

**Comment by lostanlen** [comment]
I just opened PR #751, which follows the plan of option (b) above

**Pull request closed without merging**
