### PR TITLE
Warn on empty mel filters

### LINKED ISSUE #478: Warn when filterbanks are empty [was: Vanishing mel filters]
Using a combination of a low n_fft, high n_mels, and low fmax, one can obtain a mel spectrogram where some of the bins are always 0. I haven't examined the source code but my guess would be that this combination of parameters results in a mel filterbank that has some filters with a width of 0 (in fft bins).

Here's an example: https://gist.github.com/justinsalamon/c266b7f6d60140bf1ead8ea0593dc8d2

Now sure whether there's a nice numerical solution to this problem (?), but perhaps a warning should be raised when this occurs?

### PR DESCRIPTION
**Pull request by bmcfee**
Fixes #478.  A warning is issued if the mel filter bank has all-zero rows corresponding to positive frequencies.

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/482)

### CODE REVIEW

**Comment by bmcfee** [comment]
@justinsalamon wanna give this a spin?

**Comment by justinsalamon** [comment]
Sure, upon my return though (next week).

**Comment by bmcfee** [comment]
Reviewed 16 of 17 files at r2.
Review status: 16 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/482)*

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r1, 1 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/482)*

**Comment by bmcfee** [comment]
Note: there's a bit of test spam in this PR because some of the unrelated tests actually trigger the mel gap warning.

Resetting the warning filter in each submodule ensures that the warning is still displayed when the specific test for it is called.

**Pull request merged**
