### PR TITLE
[CR] DTW Symmetry

### LINKED ISSUE #581: librosa.dtw with subseq=True is not symmetric w.r.t. its inputs
cc @stefan-balke 

My expectation for subsequence matching is that implies that either `X` can be matched to a subsequence of `Y` or `Y` can be matched to a subsequence of `X`.  `librosa.dtw` doesn't exhibit this behavior:

```Python
In [1]: import librosa
In [2]: import numpy as np
In [3]: X = np.array([10., 10., 0., 1., 2., 3., 10., 10.]).reshape([1, -1])
In [4]: Y = np.arange(4).astype(float).reshape([1, -1])
In [5]: librosa.dtw(X, Y, subseq=True)
Out[5]:
(array([[ 10.,   9.,   8.,   7.],
        [ 20.,  18.,  16.,  14.],
        [ 20.,  19.,  18.,  17.],
        [ 21.,  19.,  19.,  19.],
        [ 23.,  20.,  19.,  20.],
        [ 26.,  22.,  20.,  19.],
        [ 36.,  31.,  28.,  26.],
        [ 46.,  40.,  36.,  33.]]), array([[7, 3],
        [6, 3],
        [5, 3],
        [4, 2],
        [3, 1],
        [2, 1],
        [1, 1],
        [0, 1]]))
In [6]: librosa.dtw(Y, X, subseq=True)
Out[6]:
(array([[ 10.,  10.,   0.,   1.,   2.,   3.,  10.,  10.],
        [ 19.,  19.,   1.,   0.,   1.,   3.,  12.,  19.],
        [ 27.,  27.,   3.,   1.,   0.,   1.,   9.,  17.],
        [ 34.,  34.,   6.,   3.,   1.,   0.,   7.,  14.]]), array([[3, 5],
        [2, 4],
        [1, 3],
        [0, 2]]))
```

This is in contrast to `djitw`'s behavior (my expected behavior, obviously ;)
```Python
In [7]: import djitw

In [8]: import scipy

In [9]: djitw.dtw(scipy.spatial.distance.cdist(X.T, Y.T))
Out[9]: (array([2, 3, 4, 5]), array([0, 1, 2, 3]), 0.0)

In [10]: djitw.dtw(scipy.spatial.distance.cdist(Y.T, X.T))
Out[10]: (array([0, 1, 2, 3]), array([2, 3, 4, 5]), 0.0)
```

What is the motivation for making it non-symmetric?  We should at least document it more specifically, saying that `subseq=True` allows for a subsequence of `Y` to be matched to the entirety of `X` but not vice-versa.

### LINKED ISSUE #613: librosa.dtw : question on allowable input data dimensions
I'm getting a column dimension error when they are both (1)
(12, 1) (3, 1)
Is this shape input allowed?

```
-> dtwval, path = librosa.dtw(siga, sigb, subseq=True)
(Pdb) siga
array([[  4.],
       [ 30.],
       [ 52.],
       [ 32.],
       [ 54.],
       [ 22.],
       [ 28.],
       [ 22.],
       [ 12.],
       [ 30.],
       [ 16.],
       [ 18.]])
(Pdb) sigb
array([[ 46.],
       [  6.],
       [ 14.]])
ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)
```

### PR DESCRIPTION
**Pull request by stefan-balke**
#### Reference Issue

* Fixes #613
* Fixes #581  

#### What does this implement/fix? Explain your changes.

* DTW output is now symmetric.
* DTW now raises an error when `cdist()` does not like it.

---
This change is [Reviewable](https://reviewable.io/reviews/librosa/librosa/621)

### CODE REVIEW

**Comment by stefan-balke** [comment]
@craffel it's time for CR's CR.

**Comment by craffel** [comment]
Overall looks good.  I guess librosa doesn't enforce an 80 character requirement?

Also this line:
> `D_steps = -1 * np.ones(D.shape, dtype=np.int)`
What is that doing?  I don't see how it's relevant to the input dimension or input-symmetric issues.

Also
> Reference Issue

> Fixes #613
> Fixes #613

I think you meant you fixed two different issues :)

**Comment by stefan-balke** [comment]
Thanks @craffel, hope it helps! :)

>  I guess librosa doesn't enforce an 80 character requirement?

Luckily not :)

> What is that doing? I don't see how it's relevant to the input dimension or input-symmetric issues.

Yeah, you're right.

I noticed that `np.emtpy()` is not setting a defined output for the step-size index matrix, so I thought it might be a good idea to set this to something reasonable. Maybe should have put that in a separate PR.

> I think you meant you fixed two different issues :)

Yep, fixed!

**Comment by craffel** [comment]
This PR looks good to me.

**Comment by bmcfee** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[librosa/core/dtw.py, line 198 at r1](https://reviewable.io:443/reviews/librosa/librosa/621#-KtHISC6VzcCrBrhsU08:-KtHISC6VzcCrBrhsU09:blg0lki) ([raw file](https://github.com/librosa/librosa/blob/5f670796bde149d6bac97dd38d14941cbb508f31/librosa/core/dtw.py#L198)):*
> ```Python
>             raise ParameterError('scipy.spatial.distance.cdist returned an error.\n'
>                                  'Please provide your input in the form X.shape=(K, N) and Y.shape=(K, M).\n'
>                                  '1-dimensional sequences should be reshaped to X.shape=(1, N) and Y.shape=(1, M).')
> ```

Please propagate the original exception message as well, so the user can determine exactly what went wrong.

---

*[tests/test_dtw.py, line 20 at r1](https://reviewable.io:443/reviews/librosa/librosa/621#-KtHIrnjjMyuuEz2ahrO:-KtHIrnjjMyuuEz2ahrP:bnf0cd8) ([raw file](https://github.com/librosa/librosa/blob/5f670796bde149d6bac97dd38d14941cbb508f31/tests/test_dtw.py#L20)):*
> ```Python
>     Y = np.array([[2], [0], [0], [8], [7], [2]])
> 
>     assert_raises(librosa.util.exceptions.ParameterError, librosa.dtw, X=X, Y=Y)
> ```

Not a big deal, but the rest of the tests use the `@raises` decorator for this, which makes the code a bit easier to read.  It'd be nice to stick to that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
I had a couple of nitpicks, but otherwise looks good.

**Comment by stefan-balke** [comment]
*[librosa/core/dtw.py, line 198 at r1](https://reviewable.io:443/reviews/librosa/librosa/621#-KtHISC6VzcCrBrhsU08:-KtHLaortQWuk66ZwoCB:b-sjhr7i) ([raw file](https://github.com/librosa/librosa/blob/5f670796bde149d6bac97dd38d14941cbb508f31/librosa/core/dtw.py#L198)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Please propagate the original exception message as well, so the user can determine exactly what went wrong.
</blockquote></details>

If I do this it will be there twice.
This is the output atm:

```
Traceback (most recent call last):
  File "/Users/balke/Development/librosa_dev/librosa/core/dtw.py", line 194, in dtw
    C = cdist(X.T, Y.T, metric=metric)
  File "/Users/balke/miniconda3/envs/librosa_dev/lib/python3.6/site-packages/scipy/spatial/distance.py", line 2136, in cdist
    raise ValueError('XA and XB must have the same number of columns '
ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_dtw.py", line 155, in <module>
    test_1d_input()
  File "tests/test_dtw.py", line 19, in test_1d_input
    librosa.dtw(X=X, Y=Y)
  File "/Users/balke/Development/librosa_dev/librosa/core/dtw.py", line 196, in dtw
    raise ParameterError('scipy.spatial.distance.cdist returned an error.\n'
librosa.util.exceptions.ParameterError: scipy.spatial.distance.cdist returned an error.
Please provide your input in the form X.shape=(K, N) and Y.shape=(K, M).
1-dimensional sequences should be reshaped to X.shape=(1, N) and Y.shape=(1, M).
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by stefan-balke** [comment]
*[tests/test_dtw.py, line 20 at r1](https://reviewable.io:443/reviews/librosa/librosa/621#-KtHIrnjjMyuuEz2ahrO:-KtHLnvrUyS8urUzwjlD:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/5f670796bde149d6bac97dd38d14941cbb508f31/tests/test_dtw.py#L20)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Not a big deal, but the rest of the tests use the `@raises` decorator for this, which makes the code a bit easier to read.  It'd be nice to stick to that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[librosa/core/dtw.py, line 198 at r1](https://reviewable.io:443/reviews/librosa/librosa/621#-KtH_gkgwz9VNGN-75bc:-KtH_gkgwz9VNGN-75bd:b1qckvh) ([raw file](https://github.com/librosa/librosa/blob/5f670796bde149d6bac97dd38d14941cbb508f31/librosa/core/dtw.py#L198)):*
> ```Python
>             raise ParameterError('scipy.spatial.distance.cdist returned an error.\n'
>                                  'Please provide your input in the form X.shape=(K, N) and Y.shape=(K, M).\n'
>                                  '1-dimensional sequences should be reshaped to X.shape=(1, N) and Y.shape=(1, M).')
> ```

sorry, didn't mean to close this out --

A bare raise from within the catch block interrupts the call stack in not-totally-useful ways.  A better way to do this is via `six.reraise` (which masks the python 3ism of `raise from` for re-raising exceptions).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
[pinging @stefan-balke back on this, since it's been a couple of weeks]

**Comment by stefan-balke** [comment]
Sorry, gonna squeeze it in within the next couple of days.

**Comment by stefan-balke** [comment]
*[librosa/core/dtw.py, line 198 at r1](https://reviewable.io:443/reviews/librosa/librosa/621#-KtH_gkgwz9VNGN-75bc:-Kv862XHC5c-HACVHqdo:b-oh8k1f) ([raw file](https://github.com/librosa/librosa/blob/5f670796bde149d6bac97dd38d14941cbb508f31/librosa/core/dtw.py#L198)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

sorry, didn't mean to close this out --

A bare raise from within the catch block interrupts the call stack in not-totally-useful ways.  A better way to do this is via `six.reraise` (which masks the python 3ism of `raise from` for re-raising exceptions).

</blockquote></details>

You mean like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/test_dtw.py, line 65 at r2](https://reviewable.io:443/reviews/librosa/librosa/621#-Kv883PNG45mdD4Zjo7J:-Kv883PNG45mdD4Zjo7K:b-nsktxx) ([raw file](https://github.com/librosa/librosa/blob/aada6fbbb1c5dd45f127a8be91f1caeb5569c454/tests/test_dtw.py#L65)):*
> ```Python
> def test_dtw_incompatible_args():
>     librosa.dtw(C=1, X=1, Y=1)
>     librosa.dtw(C=None, X=None, Y=None)
> ```

these should be two separate tests.  If the first one raises, the whole thing will abort without running the second one.

This wasn't a problem for the previous implementation, but separating them will make the eventual migration to pytest easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
Hey, looks almost perfect!

I ended up merging the numba branch this week, so there's now a conflict relating to `optional_jit -> jit`.  Please rebase and fix the conflict in addition to the minor test fix I suggested.

**Comment by stefan-balke** [comment]
*[tests/test_dtw.py, line 65 at r2](https://reviewable.io:443/reviews/librosa/librosa/621#-Kv883PNG45mdD4Zjo7J:-Kv8ITh8V5IRwGioWMj_:b-896fix) ([raw file](https://github.com/librosa/librosa/blob/aada6fbbb1c5dd45f127a8be91f1caeb5569c454/tests/test_dtw.py#L65)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

these should be two separate tests.  If the first one raises, the whole thing will abort without running the second one.

This wasn't a problem for the previous implementation, but separating them will make the eventual migration to pytest easier.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by stefan-balke** [comment]
Okay, thanks.

This should do it!

**Comment by bmcfee** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621#-:-Kv8YupcZBDPce4qyimQ:bnfp4nl)*

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librosa/librosa/621)*

**Comment by bmcfee** [comment]
Thanks @stefan-balke !

**Comment by craffel** [comment]
Thanks dudes!!

**Pull request merged**
